// Generated by the design-sheets round-trip. Do not edit by hand.
// Hand-authored seed for the find_the_dog port. Leaves are asset ids (basename
// of a file in design/assets/, ext stripped); the runtime uses the byte-identical
// public/ui copies so the first v2 pass preserves the v1 visuals.
export const assets = {
  home: {
    banner: "home-banner-mascot-runtime",
    backgroundFeather: "background-feather",
    noAds: "no-ads-runtime",
    patternMotif: "pattern-motif",
    playButton: "play-level-button-runtime",
  },
  navigation: {
    threeSlot: "nav-bar-3",
    fourSlot: "nav-bar-4",
    fiveSlot: "nav-bar-5",
  },
  surfaces: {
    textures: {
      canvas: "canvas-cream-seamless",
      olive: "painted-olive-seamless",
      sky: "painted-sky-seamless",
      honey: "wood-honey-seamless",
    },
    nineSlice: {
      panelHoney: "panel-honey-9s",
      panelOlive: "panel-olive-9s",
      buttonOlive: "button-olive-9s",
      buttonSky: "button-sky-9s",
    },
  },
  achievements: {
    shortcut: "achievement-shortcut-runtime",
    completion: "achievement-completion",
    birds: "achievement-birds",
    mastery: "achievement-mastery",
    progression: "achievement-progression",
    streak: "achievement-streak",
  },
  levelNode: {
    default: "level-node-locked-runtime",
    locked: "level-node-locked-bones-runtime",
    currentTeal: "level-node-current-teal-runtime",
    completed: "level-node-complete-runtime",
  },
  hud: {
    coin: "icon_coin",
    heart: "icon_heart",
    streakFlame: "icon_streak_flame",
    hint: "icon_hint_magnifier",
    magnifier: "magnifier-runtime",
    settings: "settings-icon-runtime",
    settingsGear: "icon_settings_gear",
    shop: "shop-icon-runtime",
    back: "back_button",
  },
  resultModal: {
    detectiveComplete: "dog-detective-complete",
    detectiveCrying: "dog-detective-crying",
    rewardedAdBadge: "rewarded-ad-badge",
    title: "level-complete-title",
  },
  settings: {
    home: "settings_icon_home",
    music: "settings_icon_music",
    sound: "settings_icon_sound",
    vibration: "settings_icon_vibration",
  },
  shop: {
    coinPacks: {
      tier1: "shop_coin_pack_1",
      tier2: "shop_coin_pack_2",
      tier3: "shop_coin_pack_3",
      tier4: "shop_coin_pack_4",
      tier5: "shop_coin_pack_5",
      tier6: "shop_coin_pack_6",
    },
    hintPacks: {
      small: "shop_hint_pack_small",
      medium: "shop_hint_pack_medium",
      large: "shop_hint_pack_large",
    },
    noAds: "shop_no_ads",
    noAdsPremium: "shop_no_ads_premium",
    vipBundle: "shop_vip_bundle",
  },
  boot: {
    mascot: "dog-detective-openai",
  },
} as const;

export type AssetSlotGroup = keyof typeof assets;
