// Mage Master copy. Runtime reads keys; visible strings live here only.
export const copyLocale = "en";

export const copy = {
  "game.title": "Mage Master",
  "menu.subtitle": "Summon. Equip. Push deeper.",
  "menu.play": "Play",
  "menu.level": "Level",
  "menu.levelShort": "Lv",
  "menu.stage": "Stage",
  "menu.locked": "Locked",
  "menu.cleared": "Cleared",
  "menu.next": "Next",
  "menu.progression": "Level ladder",
  "menu.loading": "Loading levels",
  "menu.noEnergy": "Out of energy. Next in {seconds}s.",
  "nav.home": "Home",
  "nav.rift": "Rift",
  "nav.mages": "Mages",
  "nav.settings": "Settings",
  "currency.energy": "Energy",
  "currency.gold": "Gold",
  "currency.crystals": "Crystals",
  "currency.gems": "Gems",
  "currency.energyFull": "Full",
  "rift.title": "Summon Rift",
  "rift.tier": "Rift tier {tier}",
  "rift.maxTier": "Max tier",
  "rift.pull": "Summon",
  "rift.pullCost": "{cost} crystals",
  "rift.odds": "Pull odds",
  "rift.nextOdds": "Next",
  "rift.nowOdds": "Now",
  "rift.upgrade": "Upgrade",
  "rift.upgradeCost": "{gold} gold · {time}",
  "rift.upgrading": "Upgrading · {time}",
  "rift.skip": "Skip for {gems} gems",
  "rift.skipOne": "Skip for 1 gem",
  "rift.ready": "Upgrade complete",
  "rift.blurb": "Better odds pull rarer gear. Rarer gear clears deeper levels.",
  "rift.needCrystals": "Not enough crystals",
  "rift.needGold": "Not enough gold",
  "rift.needGems": "Not enough gems",
  "reveal.title": "Summoned",
  "reveal.use": "Use",
  "reveal.discard": "Discard for {gold} gold",
  "reveal.replaces": "Replaces {name} ({gold} gold)",
  "reveal.for": "For the {mage}",
  "reveal.weapon": "Weapon",
  "reveal.armor": "Armor",
  "mages.title": "Mages",
  "mages.weapon": "Weapon",
  "mages.armor": "Armor",
  "mages.power": "Power",
  "mages.blurb": "Mages never level. All power comes from their two items.",
  "mage.tank.name": "Bastion",
  "mage.warrior.name": "Ember",
  "mage.support.name": "Sage",
  "mage.tank.role": "Tank",
  "mage.warrior.role": "Warrior",
  "mage.support.role": "Support",
  "item.close": "Close",
  "stat.hp": "HP",
  "stat.hpRegen": "HP Regen",
  "stat.dodge": "Dodge",
  "stat.block": "Block",
  "stat.atk": "ATK",
  "stat.def": "DEF",
  "stat.atkSpeed": "Attack Speed",
  "stat.critChance": "Crit Chance",
  "stat.critDamage": "Crit Damage",
  "stat.moveSpeed": "Move Speed",
  "rarity.common": "Common",
  "rarity.uncommon": "Uncommon",
  "rarity.rare": "Rare",
  "rarity.epic": "Epic",
  "rarity.legendary": "Legendary",
  "rarity.mythic": "Mythic",
  "rarity.immortal": "Immortal",
  "rarity.astral": "Astral",
  "rarity.celestial": "Celestial",
  "rarity.ultimate": "Ultimate",
  "element.fire": "Fire",
  "element.ice": "Ice",
  "element.lightning": "Lightning",
  "element.arcane": "Arcane",
  "element.fire.effect": "Burn: damage over time",
  "element.ice.effect": "Chill: slows attack and move speed",
  "element.lightning.effect": "Chain: arcs to a nearby enemy",
  "element.arcane.effect": "Pierce: ignores half of DEF",
  "range.melee": "Melee",
  "range.ranged": "Ranged",
  "pattern.single": "Single target",
  "pattern.aoe": "Area",
  "enemy.goblin_grunt.name": "Goblin",
  "enemy.goblin_archer.name": "Goblin archer",
  "enemy.goblin_chief.name": "Goblin chief",
  "enemy.wolf.name": "Wolf",
  "enemy.wolf_alpha.name": "Alpha wolf",
  "enemy.slime.name": "Slime",
  "enemy.slime_king.name": "Slime king",
  "battle.level": "Level {level}",
  "battle.stage": "Stage {stage} / {count}",
  "battle.pause": "Pause",
  "battle.stageClear": "Stage clear",
  "battle.boss": "Boss",
  "battle.speed": "Speed",
  "battle.speed1": "1x",
  "battle.speed2": "2x",
  "pause.title": "Paused",
  "pause.resume": "Resume",
  "pause.settings": "Settings",
  "pause.quit": "Give up",
  "win.title": "Victory",
  "win.eyebrow": "Level {level} cleared",
  "win.message": "The next level is open.",
  "win.firstClear": "First clear: +{gems} gems",
  "win.next": "Next level",
  "win.home": "Home",
  "fail.title": "Defeat",
  "fail.eyebrow": "Level {level}",
  "fail.message": "All three mages fell. Replay an earlier level for crystals, or summon stronger gear.",
  "fail.retry": "Retry",
  "fail.home": "Home",
  "result.loot": "Loot",
  "offline.title": "Welcome",
  "offline.message": "Your camp earned income while you were away for {time}.",
  "offline.claim": "Claim",
  "settings.title": "Settings",
  "settings.back": "Back",
  "settings.music": "Music",
  "settings.sfx": "Sound effects",
  "settings.haptics": "Haptics",
  "settings.reset": "Reset save",
  "settings.resetConfirm": "Tap again to confirm the reset",
  "toast.equipped": "{name} equipped on {mage}",
  "hint.rift": "Crystals earned. Visit the Rift to summon gear.",
  "toast.discarded": "+{gold} gold",
  "toast.upgradeStarted": "Rift upgrade started",
  "toast.upgradeDone": "Rift reached tier {tier}",
  "time.seconds": "{s}s",
  "time.minutes": "{m}m {s}s",
  "time.hours": "{h}h {m}m",
} as const;

export type CopyKey = keyof typeof copy;

export function fill(key: CopyKey, values: Record<string, string | number>): string {
  let text: string = copy[key];
  for (const [k, v] of Object.entries(values)) text = text.split(`{${k}}`).join(String(v));
  return text;
}
