// Generated by design-sheets ts-copy-module codegen. Do not edit by hand.
export const copyLocale = "en";

export const copy = {
  "game.title": "Tap Ten",
  "board.label": "Tap Ten board",
  "menu.play": "Play",
  "action.restart": "Restart",
  "action.menu": "Menu",
  "action.pause": "Pause",
  "action.resume": "Resume",
  "hud.score": "Score",
  "hud.misses": "Misses",
  "hud.scoreValue": "{score}/{goal}",
  "hud.missValue": "{misses}/{limit}",
  "state.menu": "Ready",
  "state.playing": "Tap the lit tile",
  "state.paused": "Paused",
  "state.win": "Ten hits",
  "state.fail": "Too many misses",
  "state.settings": "Settings",
} as const;

export type CopyKey = keyof typeof copy;
