// Generated by design-sheets ts-copy-module codegen. Do not edit by hand.
export const copyLocale = "en";

export const copy = {
  "game.title": "Arrow",
  "menu.play": "Play",
  "menu.levelButton": "Level",
  "menu.settings": "Settings",
  "menu.saga": "40 authored levels",
  "saga.loading": "Loading levels",
  "settings.title": "Settings",
  "settings.body": "Progress follows the authored saga order.",
  "settings.hint": "Hint",
  "settings.restart": "Restart Level",
  "settings.restartAll": "Restart From Level 1",
  "settings.juice": "Juice Tuning",
  "settings.mute": "Mute",
  "settings.unmute": "Unmute",
  "settings.close": "Close",
  "settings.closeGlyph": "\u00d7",
  "pause.title": "Paused",
  "pause.resume": "Resume",
  "pause.settings": "Settings",
  "pause.quit": "Quit",
  "result.win.title": "CLEARED",
  "result.win.message": "Nice route.",
  "result.win.next": "Next",
  "result.win.replay": "Replay",
  "result.win.finish": "Finish",
  "result.lose.title": "OUT OF MOVES",
  "result.lose.message": "Try a different arrow order.",
  "result.lose.retry": "Retry",
  "result.lose.quit": "Quit",
  "result.finale.title": "ALL 40 CLEARED",
  "result.finale.message": "Every authored arrow puzzle is complete.",
  "result.finale.action": "Play Again",
} as const;

export type CopyKey = keyof typeof copy;
