// scenes/shell.js — DERIVED canonical phaser-native runtime projection.
// Do not edit. Deterministically derived from the accepted Editor-generated
// TypeScript graph by the U5 publisher (types + user-code markers stripped).
// Binds Phaser from the runtime global/local contract and exports a stable
// seven-state registry + bootstrap for the browser render proof.
const Phaser = globalThis.Phaser;

class Semantic {
    constructor(gameObject) {
        this.fabSemanticId = "";
        this.fabRole = "";
        this.fabBinding = "";
        this.fabSlot = "";
        this.fabVariant = "";
        this.gameObject = gameObject;
        gameObject["__Semantic"] = this;
    }
    static getComponent(gameObject) {
        return gameObject["__Semantic"];
    }
}

class Menu extends Phaser.Scene {
    constructor() {
        super("Menu");
    }
    preload() {
        this.load.pack("asset-pack", "asset-pack.json");
    }
    build() {
        const menu_fab_backdrop = this.add.rectangle(195, 422, 390, 844);
        menu_fab_backdrop.isFilled = true;
        menu_fab_backdrop.fillColor = 16250607;
        const menu_fab_header_band = this.add.rectangle(195, 1, 1, 1);
        menu_fab_header_band.isFilled = true;
        menu_fab_header_band.fillColor = 16250607;
        menu_fab_header_band.fillAlpha = 0;
        const menu_fab_counter = this.add.rectangle(20, 34, 144, 56);
        menu_fab_counter.setOrigin(0, 0);
        menu_fab_counter.isFilled = true;
        menu_fab_counter.fillColor = 1519682;
        menu_fab_counter.isStroked = true;
        menu_fab_counter.strokeColor = 3563376;
        menu_fab_counter.strokeAlpha = 0.7;
        menu_fab_counter.lineWidth = 2;
        menu_fab_counter.setRounded(28);
        const menu_fab_balance = this.add.text(108, 62, "", {});
        menu_fab_balance.setOrigin(0.5, 0.5);
        menu_fab_balance.text = "25 Coins";
        menu_fab_balance.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "17px" });
        const menu_fab_subtitle = this.add.text(195, 155, "", {});
        menu_fab_subtitle.setOrigin(0.5, 0.5);
        menu_fab_subtitle.text = "A small adventure begins here.";
        menu_fab_subtitle.setStyle({ "color": "#3d5968", "fontFamily": "kenney_future_narrow" });
        const menu_fab_hero_card = this.add.rectangle(195, 300, 350, 210);
        menu_fab_hero_card.isFilled = true;
        menu_fab_hero_card.fillColor = 14150892;
        menu_fab_hero_card.isStroked = true;
        menu_fab_hero_card.strokeColor = 11257804;
        menu_fab_hero_card.lineWidth = 2;
        menu_fab_hero_card.setRounded(28);
        const menu_fab_hero_label = this.add.text(48, 242, "", {});
        menu_fab_hero_label.setOrigin(0, 0.5);
        menu_fab_hero_label.text = "TRAIL 2";
        menu_fab_hero_label.setStyle({ "color": "#3d5968", "fontFamily": "kenney_future_narrow" });
        const menu_fab_hero_title = this.add.text(48, 278, "", {});
        menu_fab_hero_title.setOrigin(0, 0.5);
        menu_fab_hero_title.text = "Find the next step";
        menu_fab_hero_title.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "20px" });
        const menu_fab_hero_copy = this.add.text(48, 320, "", {});
        menu_fab_hero_copy.setOrigin(0, 0.5);
        menu_fab_hero_copy.text = "The trail is ready.";
        menu_fab_hero_copy.setStyle({ "color": "#3d5968", "fontFamily": "kenney_future_narrow" });
        const menu_fab_hero_sun = this.add.rectangle(318, 238, 48, 48);
        menu_fab_hero_sun.isFilled = true;
        menu_fab_hero_sun.fillColor = 16772514;
        menu_fab_hero_sun.setRounded(24);
        const menu_fab_hero_hill_far = this.add.rectangle(274, 358, 150, 54);
        menu_fab_hero_hill_far.isFilled = true;
        menu_fab_hero_hill_far.fillColor = 10211249;
        menu_fab_hero_hill_far.setRounded(27);
        const menu_fab_hero_hill_near = this.add.rectangle(310, 362, 86, 54);
        menu_fab_hero_hill_near.isFilled = true;
        menu_fab_hero_hill_near.fillColor = 6137727;
        menu_fab_hero_hill_near.setRounded(27);
        const menu_fab_hero_path = this.add.rectangle(260, 357, 30, 56);
        menu_fab_hero_path.isFilled = true;
        menu_fab_hero_path.fillColor = 16049335;
        menu_fab_hero_path.setRounded(15);
        const menu_fab_hero_node_halo = this.add.rectangle(1, 1, 1, 1);
        menu_fab_hero_node_halo.isFilled = true;
        menu_fab_hero_node_halo.fillColor = 16250607;
        menu_fab_hero_node_halo.fillAlpha = 0;
        menu_fab_hero_node_halo.setRounded(38);
        const menu_fab_hero_node = this.add.image(1, 1, "progression_node_current");
        menu_fab_hero_node.scaleX = 0.01;
        menu_fab_hero_node.scaleY = 0.01;
        menu_fab_hero_node.visible = false;
        const menu_fab_hero_flag_pole = this.add.rectangle(309, 286, 6, 78);
        menu_fab_hero_flag_pole.isFilled = true;
        menu_fab_hero_flag_pole.fillColor = 2061917;
        menu_fab_hero_flag_pole.setRounded(3);
        const menu_fab_hero_flag = this.add.rectangle(326, 260, 40, 28);
        menu_fab_hero_flag.isFilled = true;
        menu_fab_hero_flag.fillColor = 1339983;
        menu_fab_hero_flag.setRounded(7);
        const menu_fab_progression_card = this.add.rectangle(195, 560, 350, 220);
        menu_fab_progression_card.isFilled = true;
        menu_fab_progression_card.isStroked = true;
        menu_fab_progression_card.strokeColor = 11257804;
        menu_fab_progression_card.strokeAlpha = 0.8;
        menu_fab_progression_card.lineWidth = 2;
        menu_fab_progression_card.setRounded(28);
        const menu_fab_progress_path_left = this.add.rectangle(148, 569, 94, 8);
        menu_fab_progress_path_left.isFilled = true;
        menu_fab_progress_path_left.fillColor = 1339983;
        menu_fab_progress_path_left.setRounded(4);
        const menu_fab_progress_path_right = this.add.rectangle(242, 569, 94, 8);
        menu_fab_progress_path_right.isFilled = true;
        menu_fab_progress_path_right.fillColor = 14216932;
        menu_fab_progress_path_right.setRounded(4);
        const menu_fab_node_completed_surface = this.add.rectangle(101, 557, 64, 64);
        menu_fab_node_completed_surface.isFilled = true;
        menu_fab_node_completed_surface.fillColor = 7517582;
        menu_fab_node_completed_surface.setRounded(32);
        const menu_fab_node_completed_icon = this.add.image(101, 557, "icon_control_confirm");
        menu_fab_node_completed_icon.scaleX = 0.36;
        menu_fab_node_completed_icon.scaleY = 0.36;
        const menu_fab_node_current_halo = this.add.rectangle(195, 591, 76, 76);
        menu_fab_node_current_halo.isFilled = true;
        menu_fab_node_current_halo.fillColor = 14216932;
        menu_fab_node_current_halo.setRounded(38);
        const menu_fab_node_current_label = this.add.text(195, 632, "", {});
        menu_fab_node_current_label.setOrigin(0.5, 0.5);
        menu_fab_node_current_label.text = "CURRENT · 2";
        menu_fab_node_current_label.setStyle({ "color": "#1f765d", "fontFamily": "kenney_future_narrow" });
        const menu_fab_node_locked_surface = this.add.rectangle(289, 557, 64, 64);
        menu_fab_node_locked_surface.isFilled = true;
        menu_fab_node_locked_surface.fillColor = 7836572;
        menu_fab_node_locked_surface.setRounded(32);
        const menu_fab_progress_copy = this.add.text(195, 654, "", {});
        menu_fab_progress_copy.setOrigin(0.5, 0.5);
        menu_fab_progress_copy.text = "TRAIL PROGRESS";
        menu_fab_progress_copy.setStyle({ "color": "#1f765d", "fontFamily": "kenney_future_narrow" });
        const menu_fab_dock = this.add.rectangle(195, 844, 390, 144);
        menu_fab_dock.setOrigin(0.5, 1);
        menu_fab_dock.isFilled = true;
        const menu_fab_shop_shadow = this.add.rectangle(63, 762, 104, 86);
        menu_fab_shop_shadow.isFilled = true;
        menu_fab_shop_shadow.fillColor = 1519682;
        menu_fab_shop_shadow.fillAlpha = 0.14;
        menu_fab_shop_shadow.setRounded(20);
        const menu_fab_play_shadow = this.add.rectangle(195, 758, 154, 94);
        menu_fab_play_shadow.isFilled = true;
        menu_fab_play_shadow.fillColor = 1519682;
        menu_fab_play_shadow.fillAlpha = 0.14;
        menu_fab_play_shadow.setRounded(24);
        const menu_fab_settings_shadow = this.add.rectangle(327, 762, 104, 86);
        menu_fab_settings_shadow.isFilled = true;
        menu_fab_settings_shadow.fillColor = 1519682;
        menu_fab_settings_shadow.fillAlpha = 0.14;
        menu_fab_settings_shadow.setRounded(20);
        const menu_fab_shop_control = this.add.rectangle(63, 758, 104, 86);
        menu_fab_shop_control.isFilled = true;
        menu_fab_shop_control.fillColor = 3563376;
        menu_fab_shop_control.isStroked = true;
        menu_fab_shop_control.strokeColor = 2061917;
        menu_fab_shop_control.strokeAlpha = 0.55;
        menu_fab_shop_control.lineWidth = 2;
        menu_fab_shop_control.setRounded(20);
        const menu_fab_play_control = this.add.rectangle(195, 754, 154, 94);
        menu_fab_play_control.isFilled = true;
        menu_fab_play_control.fillColor = 1339983;
        menu_fab_play_control.setRounded(24);
        const menu_fab_settings_control = this.add.rectangle(327, 758, 104, 86);
        menu_fab_settings_control.isFilled = true;
        menu_fab_settings_control.fillColor = 3563376;
        menu_fab_settings_control.isStroked = true;
        menu_fab_settings_control.strokeColor = 2061917;
        menu_fab_settings_control.strokeAlpha = 0.55;
        menu_fab_settings_control.lineWidth = 2;
        menu_fab_settings_control.setRounded(20);
        const menu_fab_play_surface = this.add.image(195, 798, "button_surface_primary");
        menu_fab_play_surface.scaleX = 0.01;
        menu_fab_play_surface.scaleY = 0.01;
        menu_fab_play_surface.setOrigin(0.5, 1);
        menu_fab_play_surface.visible = false;
        const menu_fab_shop_surface = this.add.image(100, 730, "icon_control_surface");
        menu_fab_shop_surface.scaleX = 0.01;
        menu_fab_shop_surface.scaleY = 0.01;
        menu_fab_shop_surface.setOrigin(1, 0);
        menu_fab_shop_surface.visible = false;
        const menu_fab_settings_surface = this.add.image(346, 730, "icon_control_surface");
        menu_fab_settings_surface.scaleX = 0.01;
        menu_fab_settings_surface.scaleY = 0.01;
        menu_fab_settings_surface.setOrigin(1, 0);
        menu_fab_settings_surface.visible = false;
        const menu_fab_play_icon = this.add.image(195, 744, "icon_control_play");
        menu_fab_play_icon.scaleX = 0.4;
        menu_fab_play_icon.scaleY = 0.4;
        const menu_fab_shop_label = this.add.text(63, 788, "", {});
        menu_fab_shop_label.setOrigin(0.5, 0.5);
        menu_fab_shop_label.text = "Shop";
        menu_fab_shop_label.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const menu_fab_settings_label = this.add.text(327, 788, "", {});
        menu_fab_settings_label.setOrigin(0.5, 0.5);
        menu_fab_settings_label.text = "Settings";
        menu_fab_settings_label.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const menu_title = this.add.text(207, 116, "", {});
        menu_title.setOrigin(0.5, 0);
        menu_title.text = "Morning Shell";
        menu_title.setStyle({ "color": "#173042", "fontFamily": "kenney_future", "fontSize": "24px" });
        const menu_hero = this.add.container(195, 312.28);
        const menu_currency = this.add.image(28, 44, "counter_frame_primary_currency");
        menu_currency.scaleX = 0.36;
        menu_currency.scaleY = 0.36;
        menu_currency.setOrigin(0, 0);
        const menu_nav = this.add.container(195, 827.12);
        const menu_shop = this.add.image(83, 738, "icon_control_shop");
        menu_shop.scaleX = 0.4;
        menu_shop.scaleY = 0.4;
        menu_shop.setOrigin(1, 0);
        const menu_play = this.add.text(195, 786, "", {});
        menu_play.setOrigin(0.5, 1);
        menu_play.text = "Play";
        menu_play.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "18px" });
        const menu_settings = this.add.image(347, 738, "icon_control_settings");
        menu_settings.scaleX = 0.4;
        menu_settings.scaleY = 0.4;
        menu_settings.setOrigin(1, 0);
        const menu_progression_map = this.add.container(195, 548.6);
        const menu_node_completed = this.add.image(101.4, 557.04, "progression_node_completed");
        menu_node_completed.scaleX = 0.01;
        menu_node_completed.scaleY = 0.01;
        const menu_node_current = this.add.image(195, 590.8, "progression_node_current");
        menu_node_current.scaleX = 0.45703125;
        menu_node_current.scaleY = 0.5275;
        const menu_node_locked = this.add.image(288.6, 557.04, "progression_node_locked");
        menu_node_locked.scaleX = 0.42;
        menu_node_locked.scaleY = 0.42;
        const menu_titleSemantic = new Semantic(menu_title);
        menu_titleSemantic.fabSemanticId = "menu.title";
        menu_titleSemantic.fabRole = "screen-title";
        menu_titleSemantic.fabBinding = "presentation.static";
        menu_titleSemantic.fabSlot = "title-logo";
        menu_titleSemantic.fabVariant = "default";
        const menu_heroSemantic = new Semantic(menu_hero);
        menu_heroSemantic.fabSemanticId = "menu.hero";
        menu_heroSemantic.fabRole = "hero-art";
        menu_heroSemantic.fabBinding = "presentation.static";
        menu_heroSemantic.fabSlot = "hero-art";
        menu_heroSemantic.fabVariant = "default";
        const menu_currencySemantic = new Semantic(menu_currency);
        menu_currencySemantic.fabSemanticId = "menu.currency";
        menu_currencySemantic.fabRole = "currency-counter";
        menu_currencySemantic.fabBinding = "state.primary-currency";
        menu_currencySemantic.fabSlot = "counter-frame";
        menu_currencySemantic.fabVariant = "default";
        const menu_navSemantic = new Semantic(menu_nav);
        menu_navSemantic.fabSemanticId = "menu.nav";
        menu_navSemantic.fabRole = "bottom-nav";
        menu_navSemantic.fabBinding = "presentation.static";
        menu_navSemantic.fabVariant = "default";
        const menu_shopSemantic = new Semantic(menu_shop);
        menu_shopSemantic.fabSemanticId = "menu.shop";
        menu_shopSemantic.fabRole = "top-icon-action";
        menu_shopSemantic.fabBinding = "flow.open-shop";
        menu_shopSemantic.fabSlot = "icon-control";
        menu_shopSemantic.fabVariant = "default";
        const menu_playSemantic = new Semantic(menu_play);
        menu_playSemantic.fabSemanticId = "menu.play";
        menu_playSemantic.fabRole = "bottom-primary-action";
        menu_playSemantic.fabBinding = "flow.start-current";
        menu_playSemantic.fabSlot = "button-surface";
        menu_playSemantic.fabVariant = "default";
        const menu_settingsSemantic = new Semantic(menu_settings);
        menu_settingsSemantic.fabSemanticId = "menu.settings";
        menu_settingsSemantic.fabRole = "top-icon-action";
        menu_settingsSemantic.fabBinding = "flow.open-settings";
        menu_settingsSemantic.fabSlot = "icon-control";
        menu_settingsSemantic.fabVariant = "default";
        const menu_progression_mapSemantic = new Semantic(menu_progression_map);
        menu_progression_mapSemantic.fabSemanticId = "menu.progression-map";
        menu_progression_mapSemantic.fabRole = "progression-map";
        menu_progression_mapSemantic.fabBinding = "state.progression";
        menu_progression_mapSemantic.fabVariant = "default";
        const menu_node_completedSemantic = new Semantic(menu_node_completed);
        menu_node_completedSemantic.fabSemanticId = "menu.node.completed";
        menu_node_completedSemantic.fabRole = "progression-node";
        menu_node_completedSemantic.fabBinding = "state.progression";
        menu_node_completedSemantic.fabSlot = "progression-node";
        menu_node_completedSemantic.fabVariant = "default";
        const menu_node_currentSemantic = new Semantic(menu_node_current);
        menu_node_currentSemantic.fabSemanticId = "menu.node.current";
        menu_node_currentSemantic.fabRole = "progression-node";
        menu_node_currentSemantic.fabBinding = "flow.start-current";
        menu_node_currentSemantic.fabSlot = "progression-node";
        menu_node_currentSemantic.fabVariant = "default";
        const menu_node_lockedSemantic = new Semantic(menu_node_locked);
        menu_node_lockedSemantic.fabSemanticId = "menu.node.locked";
        menu_node_lockedSemantic.fabRole = "progression-node";
        menu_node_lockedSemantic.fabBinding = "state.progression";
        menu_node_lockedSemantic.fabSlot = "progression-node";
        menu_node_lockedSemantic.fabVariant = "default";
        this.events.emit("scene-awake");
    }
    create() {
        this.build();
    }
}

class Level extends Phaser.Scene {
    constructor() {
        super("Level");
    }
    preload() {
        this.load.pack("asset-pack", "asset-pack.json");
    }
    build() {
        const level_fab_backdrop = this.add.rectangle(195, 422, 390, 844);
        level_fab_backdrop.isFilled = true;
        level_fab_backdrop.fillColor = 16250607;
        const level_fab_header_band = this.add.rectangle(195, 52, 390, 104);
        level_fab_header_band.isFilled = true;
        level_fab_header_band.fillColor = 15199984;
        const level_fab_counter = this.add.rectangle(16, 28, 120, 48);
        level_fab_counter.setOrigin(0, 0);
        level_fab_counter.isFilled = true;
        level_fab_counter.fillColor = 1519682;
        level_fab_counter.setRounded(24);
        const level_fab_balance = this.add.text(92, 52, "", {});
        level_fab_balance.setOrigin(0.5, 0.5);
        level_fab_balance.text = "25 Coins";
        level_fab_balance.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const level_fab_gameplay_card = this.add.rectangle(195, 394, 350, 540);
        level_fab_gameplay_card.isFilled = true;
        level_fab_gameplay_card.fillColor = 14479088;
        level_fab_gameplay_card.isStroked = true;
        level_fab_gameplay_card.strokeColor = 11257804;
        level_fab_gameplay_card.lineWidth = 2;
        level_fab_gameplay_card.setRounded(28);
        const level_fab_sun = this.add.rectangle(304, 208, 50, 50);
        level_fab_sun.isFilled = true;
        level_fab_sun.fillColor = 16772514;
        level_fab_sun.setRounded(25);
        const level_fab_hill_far = this.add.rectangle(118, 566, 190, 86);
        level_fab_hill_far.isFilled = true;
        level_fab_hill_far.fillColor = 10211249;
        level_fab_hill_far.setRounded(43);
        const level_fab_hill_near = this.add.rectangle(284, 550, 168, 118);
        level_fab_hill_near.isFilled = true;
        level_fab_hill_near.fillColor = 6137727;
        level_fab_hill_near.setRounded(58);
        const level_fab_gameplay_label = this.add.text(48, 170, "", {});
        level_fab_gameplay_label.setOrigin(0, 0.5);
        level_fab_gameplay_label.text = "TRAIL CLEARING";
        level_fab_gameplay_label.setStyle({ "color": "#1f765d", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const level_fab_gameplay_title = this.add.text(48, 202, "", {});
        level_fab_gameplay_title.setOrigin(0, 0.5);
        level_fab_gameplay_title.text = "Find the next step";
        level_fab_gameplay_title.setStyle({ "color": "#173042", "fontFamily": "kenney_future", "fontSize": "20px" });
        const level_fab_gameplay_copy = this.add.text(48, 236, "", {});
        level_fab_gameplay_copy.setOrigin(0, 0.5);
        level_fab_gameplay_copy.text = "A calm path opens ahead.";
        level_fab_gameplay_copy.setStyle({ "color": "#3d5968", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const level_fab_path_a = this.add.rectangle(130, 490, 110, 10);
        level_fab_path_a.isFilled = true;
        level_fab_path_a.fillColor = 16049335;
        level_fab_path_a.setRounded(5);
        const level_fab_path_b = this.add.rectangle(185, 450, 10, 90);
        level_fab_path_b.isFilled = true;
        level_fab_path_b.fillColor = 16049335;
        level_fab_path_b.setRounded(5);
        const level_fab_path_c = this.add.rectangle(240, 410, 120, 10);
        level_fab_path_c.isFilled = true;
        level_fab_path_c.fillColor = 16049335;
        level_fab_path_c.setRounded(5);
        const level_fab_marker_start = this.add.rectangle(75, 490, 54, 54);
        level_fab_marker_start.isFilled = true;
        level_fab_marker_start.fillColor = 7517582;
        level_fab_marker_start.setRounded(27);
        const level_fab_marker_start_icon = this.add.image(75, 490, "icon_control_confirm");
        level_fab_marker_start_icon.scaleX = 0.3;
        level_fab_marker_start_icon.scaleY = 0.3;
        const level_fab_marker_current_halo = this.add.rectangle(185, 450, 66, 66);
        level_fab_marker_current_halo.isFilled = true;
        level_fab_marker_current_halo.fillColor = 14216932;
        level_fab_marker_current_halo.setRounded(33);
        const level_fab_marker_current = this.add.image(185, 450, "progression_node_current");
        level_fab_marker_current.scaleX = 0.34;
        level_fab_marker_current.scaleY = 0.34;
        const level_fab_marker_goal = this.add.rectangle(300, 410, 54, 54);
        level_fab_marker_goal.isFilled = true;
        level_fab_marker_goal.fillColor = 2061917;
        level_fab_marker_goal.setRounded(27);
        const level_fab_marker_goal_icon = this.add.image(300, 410, "icon_control_result_win");
        level_fab_marker_goal_icon.scaleX = 0.3;
        level_fab_marker_goal_icon.scaleY = 0.3;
        const level_fab_pause_control = this.add.rectangle(354, 52, 48, 48);
        level_fab_pause_control.isFilled = true;
        level_fab_pause_control.fillColor = 3563376;
        level_fab_pause_control.setRounded(16);
        const level_fab_pause_surface = this.add.image(374.4, 52, "icon_control_surface");
        level_fab_pause_surface.scaleX = 0.01;
        level_fab_pause_surface.scaleY = 0.01;
        level_fab_pause_surface.setOrigin(1, 0);
        level_fab_pause_surface.visible = false;
        const level_fab_outcome_label = this.add.text(195, 708, "", {});
        level_fab_outcome_label.setOrigin(0.5, 0.5);
        level_fab_outcome_label.text = "CHOOSE OUTCOME";
        level_fab_outcome_label.setStyle({ "color": "#3d5968", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const level_fab_test_win_control = this.add.rectangle(96, 772, 160, 56);
        level_fab_test_win_control.isFilled = true;
        level_fab_test_win_control.fillColor = 1339983;
        level_fab_test_win_control.setRounded(18);
        const level_fab_test_lose_control = this.add.rectangle(294, 772, 160, 56);
        level_fab_test_lose_control.isFilled = true;
        level_fab_test_lose_control.fillColor = 11095878;
        level_fab_test_lose_control.isStroked = true;
        level_fab_test_lose_control.strokeColor = 11095878;
        level_fab_test_lose_control.lineWidth = 2;
        level_fab_test_lose_control.setRounded(18);
        const level_fab_test_win_surface = this.add.image(8, 804, "button_surface_test_win");
        level_fab_test_win_surface.scaleX = 0.01;
        level_fab_test_win_surface.scaleY = 0.01;
        level_fab_test_win_surface.setOrigin(0, 1);
        level_fab_test_win_surface.visible = false;
        const level_fab_test_lose_surface = this.add.image(382, 804, "button_surface_test_lose");
        level_fab_test_lose_surface.scaleX = 0.01;
        level_fab_test_lose_surface.scaleY = 0.01;
        level_fab_test_lose_surface.setOrigin(1, 1);
        level_fab_test_lose_surface.visible = false;
        const level_currency = this.add.image(24, 38, "counter_frame_primary_currency");
        level_currency.scaleX = 0.28;
        level_currency.scaleY = 0.28;
        level_currency.setOrigin(0, 0);
        const level_label = this.add.text(195, 52, "", {});
        level_label.setOrigin(0.5, 0);
        level_label.text = "Trail 2";
        level_label.setStyle({ "color": "#173042", "fontFamily": "kenney_future", "fontSize": "22px" });
        const level_pause = this.add.image(372, 34, "icon_control_pause");
        level_pause.scaleX = 0.36;
        level_pause.scaleY = 0.36;
        level_pause.setOrigin(1, 0);
        const level_gameplay_region = this.add.container(195, 422);
        const level_test_win = this.add.text(36, 792, "", {});
        level_test_win.setOrigin(0, 1);
        level_test_win.text = "Win";
        level_test_win.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const level_test_lose = this.add.text(354, 792, "", {});
        level_test_lose.setOrigin(1, 1);
        level_test_lose.text = "Lose";
        level_test_lose.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const level_currencySemantic = new Semantic(level_currency);
        level_currencySemantic.fabSemanticId = "level.currency";
        level_currencySemantic.fabRole = "currency-counter";
        level_currencySemantic.fabBinding = "state.primary-currency";
        level_currencySemantic.fabSlot = "counter-frame";
        level_currencySemantic.fabVariant = "default";
        const level_labelSemantic = new Semantic(level_label);
        level_labelSemantic.fabSemanticId = "level.label";
        level_labelSemantic.fabRole = "level-label";
        level_labelSemantic.fabBinding = "state.level-label";
        level_labelSemantic.fabVariant = "default";
        const level_pauseSemantic = new Semantic(level_pause);
        level_pauseSemantic.fabSemanticId = "level.pause";
        level_pauseSemantic.fabRole = "top-icon-action";
        level_pauseSemantic.fabBinding = "flow.pause";
        level_pauseSemantic.fabSlot = "icon-control";
        level_pauseSemantic.fabVariant = "default";
        const level_gameplay_regionSemantic = new Semantic(level_gameplay_region);
        level_gameplay_regionSemantic.fabSemanticId = "level.gameplay-region";
        level_gameplay_regionSemantic.fabRole = "gameplay-region";
        level_gameplay_regionSemantic.fabBinding = "mechanic.mount";
        level_gameplay_regionSemantic.fabSlot = "gameplay-background";
        level_gameplay_regionSemantic.fabVariant = "default";
        const level_test_winSemantic = new Semantic(level_test_win);
        level_test_winSemantic.fabSemanticId = "level.test-win";
        level_test_winSemantic.fabRole = "bottom-left-test-action";
        level_test_winSemantic.fabBinding = "flow.test-win";
        level_test_winSemantic.fabSlot = "button-surface";
        level_test_winSemantic.fabVariant = "default";
        const level_test_loseSemantic = new Semantic(level_test_lose);
        level_test_loseSemantic.fabSemanticId = "level.test-lose";
        level_test_loseSemantic.fabRole = "bottom-right-test-action";
        level_test_loseSemantic.fabBinding = "flow.test-lose";
        level_test_loseSemantic.fabSlot = "button-surface";
        level_test_loseSemantic.fabVariant = "default";
        this.events.emit("scene-awake");
    }
    create() {
        this.build();
    }
}

class Shop extends Phaser.Scene {
    constructor() {
        super("Shop");
    }
    preload() {
        this.load.pack("asset-pack", "asset-pack.json");
    }
    build() {
        const shop_fab_backdrop = this.add.rectangle(195, 422, 390, 844);
        shop_fab_backdrop.isFilled = true;
        shop_fab_backdrop.fillColor = 16250607;
        const shop_fab_header_band = this.add.rectangle(195, 1, 1, 1);
        shop_fab_header_band.isFilled = true;
        shop_fab_header_band.fillColor = 16250607;
        shop_fab_header_band.fillAlpha = 0;
        const shop_fab_counter_primary = this.add.rectangle(16, 108, 172, 56);
        shop_fab_counter_primary.setOrigin(0, 0);
        shop_fab_counter_primary.isFilled = true;
        shop_fab_counter_primary.fillColor = 1519682;
        shop_fab_counter_primary.isStroked = true;
        shop_fab_counter_primary.strokeColor = 3563376;
        shop_fab_counter_primary.strokeAlpha = 0.65;
        shop_fab_counter_primary.lineWidth = 2;
        shop_fab_counter_primary.setRounded(28);
        const shop_fab_counter_secondary = this.add.rectangle(202, 108, 172, 56);
        shop_fab_counter_secondary.setOrigin(0, 0);
        shop_fab_counter_secondary.isFilled = true;
        shop_fab_counter_secondary.fillColor = 3108697;
        shop_fab_counter_secondary.isStroked = true;
        shop_fab_counter_secondary.strokeColor = 10211249;
        shop_fab_counter_secondary.strokeAlpha = 0.65;
        shop_fab_counter_secondary.lineWidth = 2;
        shop_fab_counter_secondary.setRounded(28);
        const shop_fab_grid_card = this.add.rectangle(195, 1, 1, 1);
        shop_fab_grid_card.isFilled = true;
        shop_fab_grid_card.fillColor = 16250607;
        shop_fab_grid_card.fillAlpha = 0;
        shop_fab_grid_card.setRounded(24);
        const shop_fab_section_title = this.add.text(24, 202, "", {});
        shop_fab_section_title.setOrigin(0, 0.5);
        shop_fab_section_title.text = "TRAIL SUPPLIES";
        shop_fab_section_title.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "20px" });
        const shop_fab_item_available_shadow = this.add.rectangle(104, 330, 160, 176);
        shop_fab_item_available_shadow.isFilled = true;
        shop_fab_item_available_shadow.fillColor = 1519682;
        shop_fab_item_available_shadow.fillAlpha = 0.12;
        shop_fab_item_available_shadow.setRounded(20);
        const shop_fab_item_owned_shadow = this.add.rectangle(286, 330, 160, 176);
        shop_fab_item_owned_shadow.isFilled = true;
        shop_fab_item_owned_shadow.fillColor = 1519682;
        shop_fab_item_owned_shadow.fillAlpha = 0.12;
        shop_fab_item_owned_shadow.setRounded(20);
        const shop_fab_item_locked_shadow = this.add.rectangle(1, 1, 1, 1);
        shop_fab_item_locked_shadow.isFilled = true;
        shop_fab_item_locked_shadow.fillColor = 16250607;
        shop_fab_item_locked_shadow.fillAlpha = 0;
        shop_fab_item_locked_shadow.setRounded(20);
        const shop_fab_item_available_card = this.add.rectangle(104, 326, 160, 176);
        shop_fab_item_available_card.isFilled = true;
        shop_fab_item_available_card.fillColor = 16773575;
        shop_fab_item_available_card.isStroked = true;
        shop_fab_item_available_card.strokeColor = 11257804;
        shop_fab_item_available_card.lineWidth = 2;
        shop_fab_item_available_card.setRounded(20);
        const shop_fab_item_owned_card = this.add.rectangle(286, 326, 160, 176);
        shop_fab_item_owned_card.isFilled = true;
        shop_fab_item_owned_card.fillColor = 14216932;
        shop_fab_item_owned_card.isStroked = true;
        shop_fab_item_owned_card.strokeColor = 3121013;
        shop_fab_item_owned_card.lineWidth = 2;
        shop_fab_item_owned_card.setRounded(20);
        const shop_fab_item_locked_card = this.add.rectangle(1, 1, 1, 1);
        shop_fab_item_locked_card.isFilled = true;
        shop_fab_item_locked_card.fillColor = 16250607;
        shop_fab_item_locked_card.fillAlpha = 0;
        shop_fab_item_locked_card.isStroked = true;
        shop_fab_item_locked_card.strokeColor = 16250607;
        shop_fab_item_locked_card.strokeAlpha = 0;
        shop_fab_item_locked_card.lineWidth = 0;
        shop_fab_item_locked_card.setRounded(20);
        const shop_fab_item_fourth_card = this.add.rectangle(1, 1, 1, 1);
        shop_fab_item_fourth_card.isFilled = true;
        shop_fab_item_fourth_card.fillColor = 16250607;
        shop_fab_item_fourth_card.fillAlpha = 0;
        shop_fab_item_fourth_card.setRounded(16);
        const shop_fab_item_fourth_label = this.add.text(1, 1, "", {});
        shop_fab_item_fourth_label.setOrigin(0.5, 0.5);
        shop_fab_item_fourth_label.text = " ";
        shop_fab_item_fourth_label.setStyle({ "color": "#f7f6ef", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const shop_fab_back_control = this.add.rectangle(44, 60, 56, 56);
        shop_fab_back_control.isFilled = true;
        shop_fab_back_control.fillColor = 1339983;
        shop_fab_back_control.setRounded(18);
        const shop_fab_back_surface = this.add.image(15.6, 52, "icon_control_surface");
        shop_fab_back_surface.scaleX = 0.01;
        shop_fab_back_surface.scaleY = 0.01;
        shop_fab_back_surface.setOrigin(0, 0);
        shop_fab_back_surface.visible = false;
        const shop_fab_back_glyph = this.add.image(44, 60, "icon_control_return");
        shop_fab_back_glyph.scaleX = 0.38;
        shop_fab_back_glyph.scaleY = 0.38;
        const shop_fab_primary_balance = this.add.text(127, 136, "", {});
        shop_fab_primary_balance.setOrigin(0.5, 0.5);
        shop_fab_primary_balance.text = "25 Coins";
        shop_fab_primary_balance.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow" });
        const shop_fab_secondary_gem = this.add.text(224, 136, "", {});
        shop_fab_secondary_gem.setOrigin(0.5, 0.5);
        shop_fab_secondary_gem.text = "◆";
        shop_fab_secondary_gem.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "23px" });
        const shop_fab_secondary_balance = this.add.text(316, 136, "", {});
        shop_fab_secondary_balance.setOrigin(0.5, 0.5);
        shop_fab_secondary_balance.text = "12 Gems";
        shop_fab_secondary_balance.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow" });
        const shop_fab_item_available_coin_left = this.add.rectangle(88, 279, 30, 30);
        shop_fab_item_available_coin_left.isFilled = true;
        shop_fab_item_available_coin_left.fillColor = 16772514;
        shop_fab_item_available_coin_left.setRounded(15);
        const shop_fab_item_available_coin_right = this.add.rectangle(120, 279, 30, 30);
        shop_fab_item_available_coin_right.isFilled = true;
        shop_fab_item_available_coin_right.fillColor = 15845211;
        shop_fab_item_available_coin_right.setRounded(15);
        const shop_fab_item_available_icon_surface = this.add.rectangle(104, 270, 38, 38);
        shop_fab_item_available_icon_surface.isFilled = true;
        shop_fab_item_available_icon_surface.fillColor = 1519682;
        shop_fab_item_available_icon_surface.setRounded(19);
        const shop_fab_item_available_icon = this.add.image(104, 270, "counter_frame_primary_currency");
        shop_fab_item_available_icon.scaleX = 0.24;
        shop_fab_item_available_icon.scaleY = 0.24;
        const shop_fab_item_available_detail = this.add.text(104, 351, "", {});
        shop_fab_item_available_detail.setOrigin(0.5, 0.5);
        shop_fab_item_available_detail.text = "500 Coins";
        shop_fab_item_available_detail.setStyle({ "color": "#3d5968", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const shop_fab_item_available_price_surface = this.add.rectangle(104, 386, 132, 48);
        shop_fab_item_available_price_surface.isFilled = true;
        shop_fab_item_available_price_surface.fillColor = 1339983;
        shop_fab_item_available_price_surface.setRounded(16);
        const shop_fab_item_available_price = this.add.text(104, 386, "", {});
        shop_fab_item_available_price.setOrigin(0.5, 0.5);
        shop_fab_item_available_price.text = "PREVIEW";
        shop_fab_item_available_price.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const shop_fab_item_owned_ad_tile = this.add.rectangle(286, 280, 58, 48);
        shop_fab_item_owned_ad_tile.isFilled = true;
        shop_fab_item_owned_ad_tile.setRounded(12);
        const shop_fab_item_owned_icon_surface = this.add.rectangle(1, 1, 1, 1);
        shop_fab_item_owned_icon_surface.isFilled = true;
        shop_fab_item_owned_icon_surface.fillColor = 16250607;
        shop_fab_item_owned_icon_surface.fillAlpha = 0;
        shop_fab_item_owned_icon_surface.setRounded(25);
        const shop_fab_item_owned_ad_label = this.add.text(286, 280, "", {});
        shop_fab_item_owned_ad_label.setOrigin(0.5, 0.5);
        shop_fab_item_owned_ad_label.text = "AD";
        shop_fab_item_owned_ad_label.setStyle({ "color": "#173042", "fontFamily": "kenney_future", "fontSize": "15px" });
        const shop_fab_item_owned_icon = this.add.image(306, 262, "icon_control_confirm");
        shop_fab_item_owned_icon.scaleX = 0.22;
        shop_fab_item_owned_icon.scaleY = 0.22;
        const shop_fab_item_owned_detail = this.add.text(1, 1, "", {});
        shop_fab_item_owned_detail.setOrigin(0.5, 0.5);
        shop_fab_item_owned_detail.text = " ";
        shop_fab_item_owned_detail.setStyle({ "color": "#f7f6ef", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const shop_fab_item_owned_status_surface = this.add.rectangle(286, 386, 132, 48);
        shop_fab_item_owned_status_surface.isFilled = true;
        shop_fab_item_owned_status_surface.fillColor = 12442571;
        shop_fab_item_owned_status_surface.isStroked = true;
        shop_fab_item_owned_status_surface.strokeColor = 3121013;
        shop_fab_item_owned_status_surface.lineWidth = 2;
        shop_fab_item_owned_status_surface.setRounded(16);
        const shop_fab_item_owned_status = this.add.text(286, 386, "", {});
        shop_fab_item_owned_status.setOrigin(0.5, 0.5);
        shop_fab_item_owned_status.text = "OWNED";
        shop_fab_item_owned_status.setStyle({ "color": "#1f765d", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const shop_fab_item_locked_trophy = this.add.rectangle(1, 1, 1, 1);
        shop_fab_item_locked_trophy.isFilled = true;
        shop_fab_item_locked_trophy.fillColor = 16250607;
        shop_fab_item_locked_trophy.fillAlpha = 0;
        shop_fab_item_locked_trophy.setRounded(15);
        const shop_fab_item_locked_icon_surface = this.add.rectangle(1, 1, 1, 1);
        shop_fab_item_locked_icon_surface.isFilled = true;
        shop_fab_item_locked_icon_surface.fillColor = 16250607;
        shop_fab_item_locked_icon_surface.fillAlpha = 0;
        shop_fab_item_locked_icon_surface.setRounded(25);
        const shop_fab_item_locked_trophy_icon = this.add.image(1, 1, "icon_control_result_win");
        shop_fab_item_locked_trophy_icon.scaleX = 0.01;
        shop_fab_item_locked_trophy_icon.scaleY = 0.01;
        shop_fab_item_locked_trophy_icon.visible = false;
        const shop_fab_item_locked_detail = this.add.text(1, 1, "", {});
        shop_fab_item_locked_detail.setOrigin(0.5, 0.5);
        shop_fab_item_locked_detail.text = " ";
        shop_fab_item_locked_detail.setStyle({ "color": "#f7f6ef", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const shop_fab_item_locked_status_surface = this.add.rectangle(1, 1, 1, 1);
        shop_fab_item_locked_status_surface.isFilled = true;
        shop_fab_item_locked_status_surface.fillColor = 16250607;
        shop_fab_item_locked_status_surface.fillAlpha = 0;
        shop_fab_item_locked_status_surface.isStroked = true;
        shop_fab_item_locked_status_surface.strokeColor = 16250607;
        shop_fab_item_locked_status_surface.strokeAlpha = 0;
        shop_fab_item_locked_status_surface.lineWidth = 0;
        shop_fab_item_locked_status_surface.setRounded(16);
        const shop_fab_item_locked_status = this.add.text(1, 1, "", {});
        shop_fab_item_locked_status.setOrigin(0.5, 0.5);
        shop_fab_item_locked_status.text = " ";
        shop_fab_item_locked_status.setStyle({ "color": "#f7f6ef", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const shop_fab_restore_card = this.add.rectangle(195, 742, 350, 148);
        shop_fab_restore_card.isFilled = true;
        shop_fab_restore_card.isStroked = true;
        shop_fab_restore_card.strokeColor = 11257804;
        shop_fab_restore_card.lineWidth = 2;
        shop_fab_restore_card.setRounded(22);
        const shop_fab_restore_title = this.add.text(42, 688, "", {});
        shop_fab_restore_title.setOrigin(0, 0.5);
        shop_fab_restore_title.text = "Purchases";
        shop_fab_restore_title.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "17px" });
        const shop_fab_restore_copy = this.add.text(42, 714, "", {});
        shop_fab_restore_copy.setOrigin(0, 0.5);
        shop_fab_restore_copy.text = "Restore previous purchases.";
        shop_fab_restore_copy.setStyle({ "color": "#3d5968", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const shop_fab_restore_control = this.add.rectangle(195, 775, 318, 54);
        shop_fab_restore_control.isFilled = true;
        shop_fab_restore_control.fillColor = 1339983;
        shop_fab_restore_control.setRounded(20);
        const shop_fab_restore_surface = this.add.image(195, 790, "button_surface_secondary");
        shop_fab_restore_surface.scaleX = 0.01;
        shop_fab_restore_surface.scaleY = 0.01;
        shop_fab_restore_surface.setOrigin(0.5, 1);
        shop_fab_restore_surface.visible = false;
        const shop_page = this.add.container(195, 422);
        const shop_title = this.add.text(195, 40, "", {});
        shop_title.setOrigin(0.5, 0);
        shop_title.text = "Shop";
        shop_title.setStyle({ "color": "#173042", "fontFamily": "kenney_future", "fontSize": "28px" });
        const shop_back = this.add.image(20, 36, "icon_control_back");
        shop_back.scaleX = 0.01;
        shop_back.scaleY = 0.01;
        shop_back.setOrigin(0, 0);
        const shop_currency = this.add.image(24, 118, "counter_frame_primary_currency");
        shop_currency.scaleX = 0.32;
        shop_currency.scaleY = 0.32;
        shop_currency.setOrigin(0, 0);
        const shop_currency_secondary = this.add.image(212, 118, "counter_frame_primary_currency");
        shop_currency_secondary.scaleX = 0.01;
        shop_currency_secondary.scaleY = 0.01;
        shop_currency_secondary.setOrigin(0, 0);
        const shop_grid = this.add.container(195, 447.32);
        const shop_item_available = this.add.text(104, 321, "", {});
        shop_item_available.setOrigin(0.5, 0.5);
        shop_item_available.text = "Coin Pack";
        shop_item_available.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "18px" });
        const shop_item_owned = this.add.text(286, 321, "", {});
        shop_item_owned.setOrigin(0.5, 0.5);
        shop_item_owned.text = "No Ads";
        shop_item_owned.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "18px" });
        const shop_item_locked = this.add.text(195, 526, "", {});
        shop_item_locked.scaleX = 0.01;
        shop_item_locked.scaleY = 0.01;
        shop_item_locked.setOrigin(0.5, 0.5);
        shop_item_locked.text = " ";
        shop_item_locked.setStyle({ "color": "#f7f6ef", "fontFamily": "kenney_future_narrow", "fontSize": "18px" });
        const shop_restore = this.add.text(195, 786, "", {});
        shop_restore.setOrigin(0.5, 1);
        shop_restore.text = "Restore purchases";
        shop_restore.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "17px" });
        const shop_pageSemantic = new Semantic(shop_page);
        shop_pageSemantic.fabSemanticId = "shop.page";
        shop_pageSemantic.fabRole = "page-surface";
        shop_pageSemantic.fabBinding = "presentation.static";
        shop_pageSemantic.fabVariant = "default";
        const shop_titleSemantic = new Semantic(shop_title);
        shop_titleSemantic.fabSemanticId = "shop.title";
        shop_titleSemantic.fabRole = "screen-title";
        shop_titleSemantic.fabBinding = "presentation.static";
        shop_titleSemantic.fabSlot = "title-logo";
        shop_titleSemantic.fabVariant = "default";
        const shop_backSemantic = new Semantic(shop_back);
        shop_backSemantic.fabSemanticId = "shop.back";
        shop_backSemantic.fabRole = "header-back-action";
        shop_backSemantic.fabBinding = "flow.shop-back";
        shop_backSemantic.fabSlot = "icon-control";
        shop_backSemantic.fabVariant = "default";
        const shop_currencySemantic = new Semantic(shop_currency);
        shop_currencySemantic.fabSemanticId = "shop.currency";
        shop_currencySemantic.fabRole = "currency-counter";
        shop_currencySemantic.fabBinding = "state.primary-currency";
        shop_currencySemantic.fabSlot = "counter-frame";
        shop_currencySemantic.fabVariant = "default";
        const shop_currency_secondarySemantic = new Semantic(shop_currency_secondary);
        shop_currency_secondarySemantic.fabSemanticId = "shop.currency.secondary";
        shop_currency_secondarySemantic.fabRole = "currency-counter";
        shop_currency_secondarySemantic.fabBinding = "state.secondary-currency";
        shop_currency_secondarySemantic.fabSlot = "counter-frame";
        shop_currency_secondarySemantic.fabVariant = "default";
        const shop_gridSemantic = new Semantic(shop_grid);
        shop_gridSemantic.fabSemanticId = "shop.grid";
        shop_gridSemantic.fabRole = "item-grid";
        shop_gridSemantic.fabBinding = "state.shop-items";
        shop_gridSemantic.fabVariant = "default";
        const shop_item_availableSemantic = new Semantic(shop_item_available);
        shop_item_availableSemantic.fabSemanticId = "shop.item.available";
        shop_item_availableSemantic.fabRole = "item-card";
        shop_item_availableSemantic.fabBinding = "state.shop-items";
        shop_item_availableSemantic.fabVariant = "default";
        const shop_item_ownedSemantic = new Semantic(shop_item_owned);
        shop_item_ownedSemantic.fabSemanticId = "shop.item.owned";
        shop_item_ownedSemantic.fabRole = "item-card";
        shop_item_ownedSemantic.fabBinding = "state.shop-items";
        shop_item_ownedSemantic.fabVariant = "default";
        const shop_item_lockedSemantic = new Semantic(shop_item_locked);
        shop_item_lockedSemantic.fabSemanticId = "shop.item.locked";
        shop_item_lockedSemantic.fabRole = "item-card";
        shop_item_lockedSemantic.fabBinding = "state.shop-items";
        shop_item_lockedSemantic.fabVariant = "default";
        const shop_restoreSemantic = new Semantic(shop_restore);
        shop_restoreSemantic.fabSemanticId = "shop.restore";
        shop_restoreSemantic.fabRole = "bottom-secondary-action";
        shop_restoreSemantic.fabBinding = "commerce.restore";
        shop_restoreSemantic.fabSlot = "button-surface";
        shop_restoreSemantic.fabVariant = "default";
        this.events.emit("scene-awake");
    }
    create() {
        this.build();
    }
}

class Settings extends Phaser.Scene {
    constructor() {
        super("Settings");
    }
    preload() {
        this.load.pack("asset-pack", "asset-pack.json");
    }
    build() {
        const settings_fab_backdrop = this.add.rectangle(195, 422, 390, 844);
        settings_fab_backdrop.isFilled = true;
        settings_fab_backdrop.fillColor = 16250607;
        const settings_fab_header_band = this.add.rectangle(195, 1, 1, 1);
        settings_fab_header_band.isFilled = true;
        settings_fab_header_band.fillColor = 16250607;
        settings_fab_header_band.fillAlpha = 0;
        const settings_fab_panel = this.add.rectangle(195, 366, 350, 360);
        settings_fab_panel.isFilled = true;
        settings_fab_panel.isStroked = true;
        settings_fab_panel.strokeColor = 11257804;
        settings_fab_panel.lineWidth = 2;
        settings_fab_panel.setRounded(26);
        const settings_fab_back_control = this.add.rectangle(44, 60, 56, 56);
        settings_fab_back_control.isFilled = true;
        settings_fab_back_control.fillColor = 1339983;
        settings_fab_back_control.setRounded(18);
        const settings_fab_back_surface = this.add.image(15.6, 52, "icon_control_surface");
        settings_fab_back_surface.scaleX = 0.01;
        settings_fab_back_surface.scaleY = 0.01;
        settings_fab_back_surface.setOrigin(0, 0);
        settings_fab_back_surface.visible = false;
        const settings_fab_back_glyph = this.add.image(44, 60, "icon_control_return");
        settings_fab_back_glyph.scaleX = 0.38;
        settings_fab_back_glyph.scaleY = 0.38;
        const settings_fab_section_copy = this.add.text(195, 158, "", {});
        settings_fab_section_copy.setOrigin(0.5, 0.5);
        settings_fab_section_copy.text = "Sound and feel";
        settings_fab_section_copy.setStyle({ "color": "#3d5968", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const settings_fab_divider_music = this.add.rectangle(195, 329, 300, 2);
        settings_fab_divider_music.isFilled = true;
        settings_fab_divider_music.fillColor = 15199984;
        const settings_fab_divider_sfx = this.add.rectangle(195, 414, 300, 2);
        settings_fab_divider_sfx.isFilled = true;
        settings_fab_divider_sfx.fillColor = 15199984;
        const settings_fab_toggle_music_track = this.add.rectangle(322, 286.96, 58, 30);
        settings_fab_toggle_music_track.isFilled = true;
        settings_fab_toggle_music_track.fillColor = 1339983;
        settings_fab_toggle_music_track.setRounded(15);
        const settings_fab_toggle_music_thumb = this.add.rectangle(338, 286.96, 22, 22);
        settings_fab_toggle_music_thumb.isFilled = true;
        settings_fab_toggle_music_thumb.setRounded(11);
        const settings_fab_toggle_sfx_track = this.add.rectangle(322, 371.36, 58, 30);
        settings_fab_toggle_sfx_track.isFilled = true;
        settings_fab_toggle_sfx_track.fillColor = 1339983;
        settings_fab_toggle_sfx_track.setRounded(15);
        const settings_fab_toggle_sfx_thumb = this.add.rectangle(338, 371.36, 22, 22);
        settings_fab_toggle_sfx_thumb.isFilled = true;
        settings_fab_toggle_sfx_thumb.setRounded(11);
        const settings_fab_toggle_haptics_track = this.add.rectangle(322, 455.76, 58, 30);
        settings_fab_toggle_haptics_track.isFilled = true;
        settings_fab_toggle_haptics_track.fillColor = 1339983;
        settings_fab_toggle_haptics_track.setRounded(15);
        const settings_fab_toggle_haptics_thumb = this.add.rectangle(338, 455.76, 22, 22);
        settings_fab_toggle_haptics_thumb.isFilled = true;
        settings_fab_toggle_haptics_thumb.setRounded(11);
        const settings_page = this.add.container(195, 422);
        const settings_title = this.add.text(195, 40, "", {});
        settings_title.setOrigin(0.5, 0);
        settings_title.text = "Settings";
        settings_title.setStyle({ "color": "#173042", "fontFamily": "kenney_future", "fontSize": "28px" });
        const settings_back = this.add.image(20, 36, "icon_control_back");
        settings_back.scaleX = 0.01;
        settings_back.scaleY = 0.01;
        settings_back.setOrigin(0, 0);
        const settings_music = this.add.text(160, 286.96, "", {});
        settings_music.setOrigin(0.5, 0.5);
        settings_music.text = "Music";
        settings_music.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "20px" });
        const settings_sfx = this.add.text(160, 371.36, "", {});
        settings_sfx.setOrigin(0.5, 0.5);
        settings_sfx.text = "SFX";
        settings_sfx.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "20px" });
        const settings_haptics = this.add.text(160, 455.76, "", {});
        settings_haptics.setOrigin(0.5, 0.5);
        settings_haptics.text = "Haptics";
        settings_haptics.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "20px" });
        const settings_pageSemantic = new Semantic(settings_page);
        settings_pageSemantic.fabSemanticId = "settings.page";
        settings_pageSemantic.fabRole = "page-surface";
        settings_pageSemantic.fabBinding = "presentation.static";
        settings_pageSemantic.fabVariant = "default";
        const settings_titleSemantic = new Semantic(settings_title);
        settings_titleSemantic.fabSemanticId = "settings.title";
        settings_titleSemantic.fabRole = "screen-title";
        settings_titleSemantic.fabBinding = "presentation.static";
        settings_titleSemantic.fabSlot = "title-logo";
        settings_titleSemantic.fabVariant = "default";
        const settings_backSemantic = new Semantic(settings_back);
        settings_backSemantic.fabSemanticId = "settings.back";
        settings_backSemantic.fabRole = "header-back-action";
        settings_backSemantic.fabBinding = "flow.settings-back";
        settings_backSemantic.fabSlot = "icon-control";
        settings_backSemantic.fabVariant = "default";
        const settings_musicSemantic = new Semantic(settings_music);
        settings_musicSemantic.fabSemanticId = "settings.music";
        settings_musicSemantic.fabRole = "center-toggle-action";
        settings_musicSemantic.fabBinding = "settings.music";
        settings_musicSemantic.fabSlot = "toggle-control";
        settings_musicSemantic.fabVariant = "default";
        const settings_sfxSemantic = new Semantic(settings_sfx);
        settings_sfxSemantic.fabSemanticId = "settings.sfx";
        settings_sfxSemantic.fabRole = "center-toggle-action";
        settings_sfxSemantic.fabBinding = "settings.sfx";
        settings_sfxSemantic.fabSlot = "toggle-control";
        settings_sfxSemantic.fabVariant = "default";
        const settings_hapticsSemantic = new Semantic(settings_haptics);
        settings_hapticsSemantic.fabSemanticId = "settings.haptics";
        settings_hapticsSemantic.fabRole = "center-toggle-action";
        settings_hapticsSemantic.fabBinding = "settings.haptics";
        settings_hapticsSemantic.fabSlot = "toggle-control";
        settings_hapticsSemantic.fabVariant = "default";
        this.events.emit("scene-awake");
    }
    create() {
        this.build();
    }
}

class Pause extends Phaser.Scene {
    constructor() {
        super("Pause");
    }
    preload() {
        this.load.pack("asset-pack", "asset-pack.json");
    }
    build() {
        const pause_fab_backdrop = this.add.rectangle(195, 422, 390, 844);
        pause_fab_backdrop.isFilled = true;
        pause_fab_backdrop.fillColor = 16250607;
        const pause_fab_gameplay_card = this.add.rectangle(195, 370, 350, 610);
        pause_fab_gameplay_card.isFilled = true;
        pause_fab_gameplay_card.fillColor = 14479088;
        pause_fab_gameplay_card.setRounded(28);
        const pause_fab_gameplay_sun = this.add.rectangle(303, 190, 48, 48);
        pause_fab_gameplay_sun.isFilled = true;
        pause_fab_gameplay_sun.fillColor = 16772514;
        pause_fab_gameplay_sun.setRounded(24);
        const pause_fab_gameplay_hill = this.add.rectangle(264, 600, 200, 112);
        pause_fab_gameplay_hill.isFilled = true;
        pause_fab_gameplay_hill.fillColor = 6137727;
        pause_fab_gameplay_hill.setRounded(56);
        const pause_fab_scrim = this.add.rectangle(195, 422, 390, 844);
        pause_fab_scrim.isFilled = true;
        pause_fab_scrim.fillColor = 1583670;
        pause_fab_scrim.fillAlpha = 0.42;
        const pause_fab_card = this.add.rectangle(195, 454, 340, 510);
        pause_fab_card.isFilled = true;
        pause_fab_card.fillColor = 16774879;
        pause_fab_card.isStroked = true;
        pause_fab_card.strokeColor = 2061917;
        pause_fab_card.lineWidth = 2;
        pause_fab_card.setRounded(28);
        const pause_fab_handle = this.add.rectangle(195, 222, 48, 5);
        pause_fab_handle.isFilled = true;
        pause_fab_handle.fillColor = 2061917;
        pause_fab_handle.fillAlpha = 0.6;
        pause_fab_handle.setRounded(3);
        const pause_fab_explainer = this.add.text(195, 344, "", {});
        pause_fab_explainer.setOrigin(0.5, 0.5);
        pause_fab_explainer.text = "Your run is safe.";
        pause_fab_explainer.setStyle({ "color": "#3d5968", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const pause_fab_resume_control = this.add.rectangle(195, 478, 292, 62);
        pause_fab_resume_control.isFilled = true;
        pause_fab_resume_control.fillColor = 1339983;
        pause_fab_resume_control.setRounded(20);
        const pause_fab_settings_control = this.add.rectangle(195, 564, 292, 62);
        pause_fab_settings_control.isFilled = true;
        pause_fab_settings_control.fillColor = 14216932;
        pause_fab_settings_control.isStroked = true;
        pause_fab_settings_control.strokeColor = 2061917;
        pause_fab_settings_control.lineWidth = 2;
        pause_fab_settings_control.setRounded(20);
        const pause_fab_home_control = this.add.rectangle(195, 650, 292, 62);
        pause_fab_home_control.isFilled = true;
        pause_fab_home_control.isStroked = true;
        pause_fab_home_control.strokeColor = 11257804;
        pause_fab_home_control.lineWidth = 2;
        pause_fab_home_control.setRounded(20);
        const pause_fab_resume_surface = this.add.image(195, 607.68, "button_surface_primary");
        pause_fab_resume_surface.scaleX = 0.01;
        pause_fab_resume_surface.scaleY = 0.01;
        pause_fab_resume_surface.setOrigin(0.5, 1);
        pause_fab_resume_surface.visible = false;
        const pause_fab_settings_surface = this.add.image(195, 692.08, "button_surface_secondary");
        pause_fab_settings_surface.scaleX = 0.01;
        pause_fab_settings_surface.scaleY = 0.01;
        pause_fab_settings_surface.setOrigin(0.5, 1);
        pause_fab_settings_surface.visible = false;
        const pause_fab_home_surface = this.add.image(195, 776.48, "button_surface_secondary");
        pause_fab_home_surface.scaleX = 0.01;
        pause_fab_home_surface.scaleY = 0.01;
        pause_fab_home_surface.setOrigin(0.5, 1);
        pause_fab_home_surface.visible = false;
        const pause_panel = this.add.text(195, 290, "", {});
        pause_panel.setOrigin(0.5, 0.5);
        pause_panel.text = "Paused";
        pause_panel.setStyle({ "color": "#173042", "fontFamily": "kenney_future", "fontSize": "28px" });
        const pause_resume = this.add.text(195, 492, "", {});
        pause_resume.setOrigin(0.5, 1);
        pause_resume.text = "Resume";
        pause_resume.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "20px" });
        const pause_settings = this.add.text(195, 578, "", {});
        pause_settings.setOrigin(0.5, 1);
        pause_settings.text = "Settings";
        pause_settings.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "20px" });
        const pause_home = this.add.text(195, 664, "", {});
        pause_home.setOrigin(0.5, 1);
        pause_home.text = "Home";
        pause_home.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "20px" });
        const pause_panelSemantic = new Semantic(pause_panel);
        pause_panelSemantic.fabSemanticId = "pause.panel";
        pause_panelSemantic.fabRole = "modal-panel";
        pause_panelSemantic.fabBinding = "presentation.static";
        pause_panelSemantic.fabSlot = "modal-frame";
        pause_panelSemantic.fabVariant = "default";
        const pause_resumeSemantic = new Semantic(pause_resume);
        pause_resumeSemantic.fabSemanticId = "pause.resume";
        pause_resumeSemantic.fabRole = "bottom-primary-action";
        pause_resumeSemantic.fabBinding = "flow.resume";
        pause_resumeSemantic.fabSlot = "button-surface";
        pause_resumeSemantic.fabVariant = "default";
        const pause_settingsSemantic = new Semantic(pause_settings);
        pause_settingsSemantic.fabSemanticId = "pause.settings";
        pause_settingsSemantic.fabRole = "bottom-secondary-action";
        pause_settingsSemantic.fabBinding = "flow.open-settings";
        pause_settingsSemantic.fabSlot = "button-surface";
        pause_settingsSemantic.fabVariant = "default";
        const pause_homeSemantic = new Semantic(pause_home);
        pause_homeSemantic.fabSemanticId = "pause.home";
        pause_homeSemantic.fabRole = "bottom-secondary-action";
        pause_homeSemantic.fabBinding = "flow.pause-home";
        pause_homeSemantic.fabSlot = "button-surface";
        pause_homeSemantic.fabVariant = "default";
        this.events.emit("scene-awake");
    }
    create() {
        this.build();
    }
}

class Win extends Phaser.Scene {
    constructor() {
        super("Win");
    }
    preload() {
        this.load.pack("asset-pack", "asset-pack.json");
    }
    build() {
        const win_fab_backdrop = this.add.rectangle(195, 422, 390, 844);
        win_fab_backdrop.isFilled = true;
        win_fab_backdrop.fillColor = 16250607;
        const win_fab_gameplay_card = this.add.rectangle(195, 370, 350, 620);
        win_fab_gameplay_card.isFilled = true;
        win_fab_gameplay_card.fillColor = 14479088;
        win_fab_gameplay_card.setRounded(28);
        const win_fab_context_level = this.add.text(195, 84, "", {});
        win_fab_context_level.setOrigin(0.5, 0.5);
        win_fab_context_level.text = "TRAIL 2";
        win_fab_context_level.setStyle({ "color": "#173042", "fontFamily": "kenney_future", "fontSize": "18px" });
        const win_fab_context_prompt = this.add.rectangle(195, 180, 300, 112);
        win_fab_context_prompt.isFilled = true;
        win_fab_context_prompt.isStroked = true;
        win_fab_context_prompt.strokeColor = 11257804;
        win_fab_context_prompt.lineWidth = 2;
        win_fab_context_prompt.setRounded(22);
        const win_fab_context_eyebrow = this.add.text(72, 154, "", {});
        win_fab_context_eyebrow.setOrigin(0, 0.5);
        win_fab_context_eyebrow.text = "NEXT STEP";
        win_fab_context_eyebrow.setStyle({ "color": "#1f765d", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const win_fab_context_copy = this.add.text(72, 194, "", {});
        win_fab_context_copy.setOrigin(0, 0.5);
        win_fab_context_copy.text = "A calm path opens ahead.";
        win_fab_context_copy.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const win_fab_context_sun = this.add.rectangle(306, 318, 48, 48);
        win_fab_context_sun.isFilled = true;
        win_fab_context_sun.fillColor = 16772514;
        win_fab_context_sun.setRounded(24);
        const win_fab_context_hill = this.add.rectangle(278, 590, 188, 112);
        win_fab_context_hill.isFilled = true;
        win_fab_context_hill.fillColor = 6137727;
        win_fab_context_hill.setRounded(56);
        const win_fab_scrim = this.add.rectangle(195, 422, 390, 844);
        win_fab_scrim.isFilled = true;
        win_fab_scrim.fillColor = 1583670;
        win_fab_scrim.fillAlpha = 0.52;
        const win_fab_card = this.add.rectangle(195, 450, 354, 520);
        win_fab_card.isFilled = true;
        win_fab_card.fillColor = 16774879;
        win_fab_card.isStroked = true;
        win_fab_card.strokeColor = 2061917;
        win_fab_card.strokeAlpha = 0.8;
        win_fab_card.lineWidth = 2;
        win_fab_card.setRounded(28);
        const win_fab_header_shadow = this.add.rectangle(1, 1, 1, 1);
        win_fab_header_shadow.isFilled = true;
        win_fab_header_shadow.fillColor = 16250607;
        win_fab_header_shadow.fillAlpha = 0;
        win_fab_header_shadow.setRounded(22);
        const win_fab_header = this.add.rectangle(1, 1, 1, 1);
        win_fab_header.isFilled = true;
        win_fab_header.fillColor = 16250607;
        win_fab_header.fillAlpha = 0;
        win_fab_header.isStroked = true;
        win_fab_header.strokeColor = 2061917;
        win_fab_header.lineWidth = 2;
        win_fab_header.setRounded(22);
        const win_fab_result_icon_surface = this.add.image(195, 170, "icon_control_surface");
        win_fab_result_icon_surface.scaleX = 0.01;
        win_fab_result_icon_surface.scaleY = 0.01;
        win_fab_result_icon_surface.visible = false;
        const win_fab_result_medal = this.add.rectangle(195, 260, 56, 56);
        win_fab_result_medal.isFilled = true;
        win_fab_result_medal.fillColor = 2061917;
        win_fab_result_medal.setRounded(28);
        const win_fab_result_icon = this.add.image(195, 260, "icon_control_result_win");
        win_fab_result_icon.scaleX = 0.28;
        win_fab_result_icon.scaleY = 0.28;
        const win_fab_confetti_a = this.add.rectangle(68, 278, 8, 18);
        win_fab_confetti_a.isFilled = true;
        win_fab_confetti_a.fillColor = 11095878;
        win_fab_confetti_a.setRounded(4);
        const win_fab_confetti_b = this.add.rectangle(102, 340, 8, 14);
        win_fab_confetti_b.isFilled = true;
        win_fab_confetti_b.fillColor = 3563376;
        win_fab_confetti_b.setRounded(4);
        const win_fab_confetti_c = this.add.rectangle(150, 270, 14, 8);
        win_fab_confetti_c.isFilled = true;
        win_fab_confetti_c.fillColor = 16772514;
        win_fab_confetti_c.setRounded(4);
        const win_fab_confetti_d = this.add.rectangle(248, 272, 8, 16);
        win_fab_confetti_d.isFilled = true;
        win_fab_confetti_d.fillColor = 6137727;
        win_fab_confetti_d.setRounded(4);
        const win_fab_confetti_e = this.add.rectangle(286, 356, 14, 8);
        win_fab_confetti_e.isFilled = true;
        win_fab_confetti_e.fillColor = 11095878;
        win_fab_confetti_e.setRounded(4);
        const win_fab_confetti_f = this.add.rectangle(332, 258, 8, 14);
        win_fab_confetti_f.isFilled = true;
        win_fab_confetti_f.fillColor = 16772514;
        win_fab_confetti_f.setRounded(4);
        const win_fab_reward_ribbon = this.add.rectangle(195, 425, 294, 110);
        win_fab_reward_ribbon.isFilled = true;
        win_fab_reward_ribbon.fillColor = 14479088;
        win_fab_reward_ribbon.isStroked = true;
        win_fab_reward_ribbon.strokeColor = 11257804;
        win_fab_reward_ribbon.lineWidth = 2;
        win_fab_reward_ribbon.setRounded(22);
        const win_fab_explainer = this.add.text(195, 457, "", {});
        win_fab_explainer.setOrigin(0.5, 0.5);
        win_fab_explainer.text = "A new route is ready.";
        win_fab_explainer.setStyle({ "color": "#3d5968", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const win_fab_claim_control = this.add.rectangle(195, 526, 294, 60);
        win_fab_claim_control.isFilled = true;
        win_fab_claim_control.fillColor = 1339983;
        win_fab_claim_control.setRounded(20);
        const win_fab_claim_double_control = this.add.rectangle(195, 608, 294, 72);
        win_fab_claim_double_control.isFilled = true;
        win_fab_claim_double_control.fillColor = 14216932;
        win_fab_claim_double_control.isStroked = true;
        win_fab_claim_double_control.strokeColor = 2061917;
        win_fab_claim_double_control.lineWidth = 2;
        win_fab_claim_double_control.setRounded(20);
        const win_fab_claim_double_icon_surface = this.add.rectangle(74, 608, 40, 40);
        win_fab_claim_double_icon_surface.isFilled = true;
        win_fab_claim_double_icon_surface.fillColor = 2061917;
        win_fab_claim_double_icon_surface.setRounded(20);
        const win_fab_claim_double_icon = this.add.image(74, 608, "icon_control_play");
        win_fab_claim_double_icon.scaleX = 0.26;
        win_fab_claim_double_icon.scaleY = 0.26;
        const win_fab_claim_surface = this.add.image(195, 650, "button_surface_primary");
        win_fab_claim_surface.scaleX = 0.01;
        win_fab_claim_surface.scaleY = 0.01;
        win_fab_claim_surface.setOrigin(0.5, 1);
        win_fab_claim_surface.visible = false;
        const win_fab_claim_double_surface = this.add.image(195, 738, "button_surface_secondary");
        win_fab_claim_double_surface.scaleX = 0.01;
        win_fab_claim_double_surface.scaleY = 0.01;
        win_fab_claim_double_surface.setOrigin(0.5, 1);
        win_fab_claim_double_surface.visible = false;
        const win_panel = this.add.text(195, 330, "", {});
        win_panel.setOrigin(0.5, 0.5);
        win_panel.text = "Trail Complete";
        win_panel.setStyle({ "color": "#173042", "fontFamily": "kenney_future", "fontSize": "22px" });
        const win_reward = this.add.text(195, 399, "", {});
        win_reward.setOrigin(0.5, 0);
        win_reward.text = "5 Coins earned";
        win_reward.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "20px" });
        const win_claim = this.add.text(195, 540, "", {});
        win_claim.setOrigin(0.5, 1);
        win_claim.text = "Claim";
        win_claim.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "20px" });
        const win_claim_double = this.add.text(218, 619, "", {});
        win_claim_double.setOrigin(0.5, 1);
        win_claim_double.text = "Watch ad · Double Coins";
        win_claim_double.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const win_next = this.add.text(195, 692.08, "", {});
        win_next.setOrigin(0.5, 1);
        win_next.visible = false;
        win_next.text = "Next";
        win_next.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future", "fontSize": "28px" });
        const win_home = this.add.text(195, 776.48, "", {});
        win_home.setOrigin(0.5, 1);
        win_home.visible = false;
        win_home.text = "Home";
        win_home.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future", "fontSize": "28px" });
        const win_panelSemantic = new Semantic(win_panel);
        win_panelSemantic.fabSemanticId = "win.panel";
        win_panelSemantic.fabRole = "result-panel";
        win_panelSemantic.fabBinding = "presentation.static";
        win_panelSemantic.fabSlot = "modal-frame";
        win_panelSemantic.fabVariant = "default";
        const win_rewardSemantic = new Semantic(win_reward);
        win_rewardSemantic.fabSemanticId = "win.reward";
        win_rewardSemantic.fabRole = "level-label";
        win_rewardSemantic.fabBinding = "state.reward-amount";
        win_rewardSemantic.fabVariant = "default";
        const win_claimSemantic = new Semantic(win_claim);
        win_claimSemantic.fabSemanticId = "win.claim";
        win_claimSemantic.fabRole = "bottom-primary-action";
        win_claimSemantic.fabBinding = "flow.claim";
        win_claimSemantic.fabSlot = "button-surface";
        win_claimSemantic.fabVariant = "default";
        const win_claim_doubleSemantic = new Semantic(win_claim_double);
        win_claim_doubleSemantic.fabSemanticId = "win.claim-double";
        win_claim_doubleSemantic.fabRole = "bottom-secondary-action";
        win_claim_doubleSemantic.fabBinding = "flow.claim-double";
        win_claim_doubleSemantic.fabSlot = "button-surface";
        win_claim_doubleSemantic.fabVariant = "default";
        const win_nextSemantic = new Semantic(win_next);
        win_nextSemantic.fabSemanticId = "win.next";
        win_nextSemantic.fabRole = "bottom-primary-action";
        win_nextSemantic.fabBinding = "flow.next";
        win_nextSemantic.fabSlot = "button-surface";
        win_nextSemantic.fabVariant = "default";
        const win_homeSemantic = new Semantic(win_home);
        win_homeSemantic.fabSemanticId = "win.home";
        win_homeSemantic.fabRole = "bottom-secondary-action";
        win_homeSemantic.fabBinding = "flow.result-home";
        win_homeSemantic.fabSlot = "button-surface";
        win_homeSemantic.fabVariant = "default";
        this.events.emit("scene-awake");
    }
    create() {
        this.build();
    }
}

class Fail extends Phaser.Scene {
    constructor() {
        super("Fail");
    }
    preload() {
        this.load.pack("asset-pack", "asset-pack.json");
    }
    build() {
        const fail_fab_backdrop = this.add.rectangle(195, 422, 390, 844);
        fail_fab_backdrop.isFilled = true;
        fail_fab_backdrop.fillColor = 16250607;
        const fail_fab_gameplay_card = this.add.rectangle(195, 370, 350, 620);
        fail_fab_gameplay_card.isFilled = true;
        fail_fab_gameplay_card.fillColor = 14479088;
        fail_fab_gameplay_card.setRounded(28);
        const fail_fab_context_level = this.add.text(195, 84, "", {});
        fail_fab_context_level.setOrigin(0.5, 0.5);
        fail_fab_context_level.text = "TRAIL 2";
        fail_fab_context_level.setStyle({ "color": "#173042", "fontFamily": "kenney_future", "fontSize": "18px" });
        const fail_fab_context_prompt = this.add.rectangle(195, 180, 300, 112);
        fail_fab_context_prompt.isFilled = true;
        fail_fab_context_prompt.isStroked = true;
        fail_fab_context_prompt.strokeColor = 11257804;
        fail_fab_context_prompt.lineWidth = 2;
        fail_fab_context_prompt.setRounded(22);
        const fail_fab_context_eyebrow = this.add.text(72, 154, "", {});
        fail_fab_context_eyebrow.setOrigin(0, 0.5);
        fail_fab_context_eyebrow.text = "TRAIL CLEARING";
        fail_fab_context_eyebrow.setStyle({ "color": "#1f765d", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const fail_fab_context_copy = this.add.text(72, 194, "", {});
        fail_fab_context_copy.setOrigin(0, 0.5);
        fail_fab_context_copy.text = "A calm path opens ahead.";
        fail_fab_context_copy.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const fail_fab_context_sun = this.add.rectangle(306, 318, 48, 48);
        fail_fab_context_sun.isFilled = true;
        fail_fab_context_sun.fillColor = 16772514;
        fail_fab_context_sun.setRounded(24);
        const fail_fab_context_hill = this.add.rectangle(278, 590, 188, 112);
        fail_fab_context_hill.isFilled = true;
        fail_fab_context_hill.fillColor = 6137727;
        fail_fab_context_hill.setRounded(56);
        const fail_fab_scrim = this.add.rectangle(195, 422, 390, 844);
        fail_fab_scrim.isFilled = true;
        fail_fab_scrim.fillColor = 1583670;
        fail_fab_scrim.fillAlpha = 0.52;
        const fail_fab_card = this.add.rectangle(195, 844, 390, 454);
        fail_fab_card.setOrigin(0.5, 1);
        fail_fab_card.isFilled = true;
        fail_fab_card.fillColor = 16774879;
        fail_fab_card.isStroked = true;
        fail_fab_card.strokeColor = 11095878;
        fail_fab_card.lineWidth = 2;
        fail_fab_card.setRounded(28);
        const fail_fab_handle = this.add.rectangle(195, 402, 48, 5);
        fail_fab_handle.isFilled = true;
        fail_fab_handle.fillColor = 11095878;
        fail_fab_handle.setRounded(3);
        const fail_fab_header_shadow = this.add.rectangle(1, 1, 1, 1);
        fail_fab_header_shadow.isFilled = true;
        fail_fab_header_shadow.fillColor = 16250607;
        fail_fab_header_shadow.fillAlpha = 0;
        fail_fab_header_shadow.setRounded(22);
        const fail_fab_header = this.add.rectangle(1, 1, 1, 1);
        fail_fab_header.isFilled = true;
        fail_fab_header.fillColor = 16250607;
        fail_fab_header.fillAlpha = 0;
        fail_fab_header.isStroked = true;
        fail_fab_header.strokeColor = 11095878;
        fail_fab_header.lineWidth = 2;
        fail_fab_header.setRounded(22);
        const fail_fab_result_medal = this.add.rectangle(346, 438, 56, 56);
        fail_fab_result_medal.isFilled = true;
        fail_fab_result_medal.fillColor = 11095878;
        fail_fab_result_medal.setRounded(28);
        const fail_fab_result_icon = this.add.image(346, 438, "icon_control_result_fail");
        fail_fab_result_icon.scaleX = 0.3;
        fail_fab_result_icon.scaleY = 0.3;
        const fail_fab_counter = this.add.rectangle(85, 490, 220, 56);
        fail_fab_counter.setOrigin(0, 0);
        fail_fab_counter.isFilled = true;
        fail_fab_counter.fillColor = 1519682;
        fail_fab_counter.isStroked = true;
        fail_fab_counter.strokeColor = 3563376;
        fail_fab_counter.strokeAlpha = 0.65;
        fail_fab_counter.lineWidth = 2;
        fail_fab_counter.setRounded(28);
        const fail_fab_balance = this.add.text(222, 518, "", {});
        fail_fab_balance.setOrigin(0.5, 0.5);
        fail_fab_balance.text = "25 Coins";
        fail_fab_balance.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "18px" });
        const fail_fab_explainer = this.add.text(195, 568, "", {});
        fail_fab_explainer.setOrigin(0.5, 0.5);
        fail_fab_explainer.text = "Choose a step and retry.";
        fail_fab_explainer.setStyle({ "color": "#3d5968", "fontFamily": "kenney_future_narrow", "fontSize": "15px" });
        const fail_fab_continue_control = this.add.rectangle(195, 628, 338, 60);
        fail_fab_continue_control.isFilled = true;
        fail_fab_continue_control.fillColor = 1339983;
        fail_fab_continue_control.setRounded(20);
        const fail_fab_retry_control = this.add.rectangle(195, 698, 338, 58);
        fail_fab_retry_control.isFilled = true;
        fail_fab_retry_control.fillColor = 14216932;
        fail_fab_retry_control.isStroked = true;
        fail_fab_retry_control.strokeColor = 2061917;
        fail_fab_retry_control.lineWidth = 2;
        fail_fab_retry_control.setRounded(20);
        const fail_fab_bundle_divider = this.add.rectangle(195, 739, 306, 2);
        fail_fab_bundle_divider.isFilled = true;
        fail_fab_bundle_divider.fillColor = 11095878;
        fail_fab_bundle_divider.fillAlpha = 0.4;
        const fail_fab_bundle_control = this.add.rectangle(195, 781, 306, 58);
        fail_fab_bundle_control.isFilled = true;
        fail_fab_bundle_control.fillColor = 16244436;
        fail_fab_bundle_control.isStroked = true;
        fail_fab_bundle_control.strokeColor = 13138018;
        fail_fab_bundle_control.strokeAlpha = 0.75;
        fail_fab_bundle_control.lineWidth = 2;
        fail_fab_bundle_control.setRounded(20);
        const fail_fab_retry_surface = this.add.image(195, 727, "button_surface_primary");
        fail_fab_retry_surface.scaleX = 0.01;
        fail_fab_retry_surface.scaleY = 0.01;
        fail_fab_retry_surface.setOrigin(0.5, 1);
        fail_fab_retry_surface.visible = false;
        const fail_fab_continue_surface = this.add.image(195, 658, "button_surface_secondary");
        fail_fab_continue_surface.scaleX = 0.01;
        fail_fab_continue_surface.scaleY = 0.01;
        fail_fab_continue_surface.setOrigin(0.5, 1);
        fail_fab_continue_surface.visible = false;
        const fail_fab_bundle_surface = this.add.image(195, 824, "button_surface_secondary");
        fail_fab_bundle_surface.scaleX = 0.01;
        fail_fab_bundle_surface.scaleY = 0.01;
        fail_fab_bundle_surface.setOrigin(0.5, 1);
        fail_fab_bundle_surface.visible = false;
        const fail_panel = this.add.text(195, 438, "", {});
        fail_panel.setOrigin(0.5, 0.5);
        fail_panel.text = "Trail Blocked";
        fail_panel.setStyle({ "color": "#173042", "fontFamily": "kenney_future", "fontSize": "20px" });
        const fail_currency = this.add.image(98, 504, "counter_frame_primary_currency");
        fail_currency.scaleX = 0.32;
        fail_currency.scaleY = 0.32;
        fail_currency.setOrigin(0, 0);
        const fail_continue_coins = this.add.text(195, 643, "", {});
        fail_continue_coins.setOrigin(0.5, 1);
        fail_continue_coins.text = "Continue · 10 Coins";
        fail_continue_coins.setStyle({ "color": "#ffffff", "fontFamily": "kenney_future_narrow", "fontSize": "19px" });
        const fail_bundle = this.add.text(195, 792, "", {});
        fail_bundle.setOrigin(0.5, 1);
        fail_bundle.text = "Rescue bundle · $4.99\nContinue this level";
        fail_bundle.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "14px" });
        const fail_retry = this.add.text(195, 713, "", {});
        fail_retry.setOrigin(0.5, 1);
        fail_retry.text = "Retry";
        fail_retry.setStyle({ "color": "#173042", "fontFamily": "kenney_future_narrow", "fontSize": "20px" });
        const fail_panelSemantic = new Semantic(fail_panel);
        fail_panelSemantic.fabSemanticId = "fail.panel";
        fail_panelSemantic.fabRole = "result-panel";
        fail_panelSemantic.fabBinding = "presentation.static";
        fail_panelSemantic.fabSlot = "modal-frame";
        fail_panelSemantic.fabVariant = "default";
        const fail_currencySemantic = new Semantic(fail_currency);
        fail_currencySemantic.fabSemanticId = "fail.currency";
        fail_currencySemantic.fabRole = "currency-counter";
        fail_currencySemantic.fabBinding = "state.primary-currency";
        fail_currencySemantic.fabSlot = "counter-frame";
        fail_currencySemantic.fabVariant = "default";
        const fail_continue_coinsSemantic = new Semantic(fail_continue_coins);
        fail_continue_coinsSemantic.fabSemanticId = "fail.continue-coins";
        fail_continue_coinsSemantic.fabRole = "bottom-secondary-action";
        fail_continue_coinsSemantic.fabBinding = "flow.continue-coins";
        fail_continue_coinsSemantic.fabSlot = "button-surface";
        fail_continue_coinsSemantic.fabVariant = "default";
        const fail_bundleSemantic = new Semantic(fail_bundle);
        fail_bundleSemantic.fabSemanticId = "fail.bundle";
        fail_bundleSemantic.fabRole = "bottom-secondary-action";
        fail_bundleSemantic.fabBinding = "commerce.bundle";
        fail_bundleSemantic.fabSlot = "button-surface";
        fail_bundleSemantic.fabVariant = "default";
        const fail_retrySemantic = new Semantic(fail_retry);
        fail_retrySemantic.fabSemanticId = "fail.retry";
        fail_retrySemantic.fabRole = "bottom-primary-action";
        fail_retrySemantic.fabBinding = "flow.retry";
        fail_retrySemantic.fabSlot = "button-surface";
        fail_retrySemantic.fabVariant = "default";
        this.events.emit("scene-awake");
    }
    create() {
        this.build();
    }
}

export const states = ["menu","level","shop","settings","pause","win","fail"];
export const scenes = { menu: Menu, level: Level, shop: Shop, settings: Settings, pause: Pause, win: Win, fail: Fail };
export function boot(config) {
  return new Phaser.Game({
    type: Phaser.AUTO,
    width: 390,
    height: 844,
    ...config,
    scene: states.map((state) => scenes[state]),
  });
}
export default { states, scenes, boot };
