export const FIND_THE_DOG_ENV_KEYS = Object.freeze([
  'VITE_FIREBASE_API_KEY',
  'VITE_FIREBASE_PROJECT_ID',
  'VITE_FIREBASE_APP_ID',
  'VITE_FIREBASE_AUTH_DOMAIN',
  'VITE_FIREBASE_STORAGE_BUCKET',
  'VITE_FIREBASE_MESSAGING_SENDER_ID',
  'VITE_FIREBASE_MEASUREMENT_ID',
  'VITE_FTD_DISABLE_REMOTE_CONFIG',
  'VITE_ENABLE_TEST_HARNESS',
  'VITE_INSITU_TOUR',
  'VITE_GAMEANALYTICS_IOS_ENABLED',
  'VITE_GAMEANALYTICS_IOS_GAME_KEY',
  'VITE_GAMEANALYTICS_IOS_SECRET_KEY',
  'VITE_GAMEANALYTICS_VERBOSE_LOGGING',
  'VITE_REVENUECAT_IOS_API_KEY',
  'VITE_REVENUECAT_ANDROID_API_KEY',
  'VITE_ADJUST_IOS_ENABLED',
  'VITE_ADJUST_IOS_APP_TOKEN',
  'VITE_ADJUST_IOS_ENVIRONMENT',
  'VITE_ADJUST_EVENT_APP_OPEN_TOKEN',
  'VITE_ADJUST_EVENT_LEVEL_START_TOKEN',
  'VITE_ADJUST_EVENT_LEVEL_COMPLETE_TOKEN',
  'VITE_ADJUST_EVENT_LEVEL_FAIL_TOKEN',
  'VITE_ADJUST_EVENT_REWARDED_WATCHED_TOKEN',
  'VITE_ADJUST_VERBOSE_LOGGING',
  'VITE_APPLOVIN_IOS_ENABLED',
  'VITE_APPLOVIN_IOS_SDK_KEY',
  'VITE_APPLOVIN_IOS_GENERAL_AUDIENCE_ONLY',
  'VITE_APPLOVIN_ANDROID_ENABLED',
  'VITE_APPLOVIN_ANDROID_SDK_KEY',
  'VITE_APPLOVIN_ANDROID_GENERAL_AUDIENCE_ONLY',
  'VITE_APPLOVIN_HAS_USER_CONSENT',
  'VITE_APPLOVIN_DO_NOT_SELL',
  'VITE_APPLOVIN_CONSENT_FLOW_ENABLED',
  'VITE_APPLOVIN_GDPR_TERMS_ALERT_ENABLED',
  'VITE_APPLOVIN_VERBOSE_LOGGING',
  'VITE_APPLOVIN_IOS_BANNER_ID',
  'VITE_APPLOVIN_IOS_INTERSTITIAL_ID',
  'VITE_APPLOVIN_IOS_REWARDED_ID',
  'VITE_APPLOVIN_ANDROID_BANNER_ID',
  'VITE_APPLOVIN_ANDROID_INTERSTITIAL_ID',
  'VITE_APPLOVIN_ANDROID_REWARDED_ID',
  'VITE_ADMOB_IOS_BANNER_ID',
  'VITE_ADMOB_IOS_INTERSTITIAL_ID',
  'VITE_ADMOB_IOS_REWARDED_ID',
  'VITE_ADMOB_ANDROID_BANNER_ID',
  'VITE_ADMOB_ANDROID_INTERSTITIAL_ID',
  'VITE_ADMOB_ANDROID_REWARDED_ID',
  'VITE_FTD_PRIVACY_POLICY_URL',
  'VITE_FTD_TERMS_URL',
  'VITE_FTD_DATA_DELETION_URL',
  'VITE_FTD_SUPPORT_URL',
  'VITE_FTD_STORE_LINK',
  'VITE_CDN_ENABLED',
  'VITE_CDN_ORIGIN_DEV',
  'VITE_CDN_ORIGIN_PROD',
  'VITE_CDN_ORIGIN_ANDROID',
  'VITE_FTD_OWNED_ANALYTICS_MIRROR_URL',
  'VITE_FTD_OWNED_ANALYTICS_MIRROR_PUBLIC_CLIENT_KEY',
]);

function intentKeys(mode) {
  const keys = ['VITE_FTD_DISABLE_REMOTE_CONFIG', 'VITE_CDN_ENABLED'];
  if (mode === 'ios') {
    keys.push(
      'VITE_GAMEANALYTICS_IOS_ENABLED',
      'VITE_ADJUST_IOS_ENABLED',
      'VITE_APPLOVIN_IOS_ENABLED',
    );
  } else {
    keys.push('VITE_APPLOVIN_ANDROID_ENABLED');
  }
  return keys;
}

function validateConditional({ values, mode, booleanValue, requireValue, invalidKeys }) {
  if (mode === 'ios' && booleanValue(values.get('VITE_GAMEANALYTICS_IOS_ENABLED')) === true) {
    requireValue('VITE_GAMEANALYTICS_IOS_GAME_KEY');
    requireValue('VITE_GAMEANALYTICS_IOS_SECRET_KEY');
  }

  if (mode === 'ios' && booleanValue(values.get('VITE_ADJUST_IOS_ENABLED')) === true) {
    requireValue('VITE_ADJUST_IOS_APP_TOKEN');
    requireValue('VITE_ADJUST_IOS_ENVIRONMENT');
    const environment = values.get('VITE_ADJUST_IOS_ENVIRONMENT');
    if (environment && !['sandbox', 'production'].includes(environment.trim().toLowerCase())) {
      invalidKeys.push('VITE_ADJUST_IOS_ENVIRONMENT');
    }
  }

  const prefix = mode === 'ios' ? 'VITE_APPLOVIN_IOS' : 'VITE_APPLOVIN_ANDROID';
  if (booleanValue(values.get(`${prefix}_ENABLED`)) === true) {
    requireValue(`${prefix}_SDK_KEY`);
    if (booleanValue(values.get(`${prefix}_GENERAL_AUDIENCE_ONLY`)) !== true) {
      invalidKeys.push(`${prefix}_GENERAL_AUDIENCE_ONLY`);
    }
  }
}

function configureMissingDryRunCase(values, mode) {
  if (mode === 'ios') {
    values.set('VITE_GAMEANALYTICS_IOS_ENABLED', 'true');
    return 'VITE_GAMEANALYTICS_IOS_SECRET_KEY';
  }
  values.set('VITE_APPLOVIN_ANDROID_ENABLED', 'true');
  values.set('VITE_APPLOVIN_ANDROID_GENERAL_AUDIENCE_ONLY', 'true');
  return 'VITE_APPLOVIN_ANDROID_SDK_KEY';
}

export const FIND_THE_DOG_POLICY = Object.freeze({
  canonicalKeys: FIND_THE_DOG_ENV_KEYS,
  intentKeys,
  validateConditional,
  configureMissingDryRunCase,
});
