"""Remove magenta keying residue from sprites lifted off a magenta plate.

The house tiers were generated by editing on a flat magenta background and then
keyed. A hard threshold leaves a rim of half-magenta pixels that reads as a
purple outline on device (caught by gate B on the tier-3 capture, not by eye).

Each offending pixel keeps its alpha - the silhouette must not change - and
takes the colour of its nearest clean visible neighbour, so a wood edge stays a
wood edge instead of turning grey.
"""
import sys
import numpy as np
from PIL import Image
from scipy import ndimage

def defringe(path: str) -> str:
    im = Image.open(path).convert("RGBA")
    a = np.asarray(im).astype(int)
    r, g, b, al = a[..., 0], a[..., 1], a[..., 2], a[..., 3]
    visible = al > 20
    fringe = visible & (r > 110) & (b > 110) & (g < r - 45) & (g < b - 45)
    if not fringe.any():
        return f"{path}: clean"
    clean = visible & ~fringe
    # nearest clean pixel for every fringe pixel
    idx = ndimage.distance_transform_edt(~clean, return_distances=False, return_indices=True)
    out = a.copy()
    for ch in range(3):
        ch_vals = a[..., ch]
        out[..., ch] = np.where(fringe, ch_vals[tuple(idx)], ch_vals)
    # soften the outermost rim so no hard reclaimed edge appears
    rim = fringe & ~ndimage.binary_erosion(visible, iterations=1)
    out[..., 3] = np.where(rim, (al * 0.75).astype(int), al)
    Image.fromarray(out.astype(np.uint8)).save(path, "WEBP", quality=92, method=6)
    return f"{path}: repaired {int(fringe.sum())} px"

for p in sys.argv[1:]:
    print(defringe(p))
