// Generated by the design-sheets round-trip. Do not edit by hand.
// Leaves are asset ids (basename of a file in design/assets/, ext stripped).
export const assets = {
  placeholder: {
    logo: "placeholder_logo",
  },
} as const;

export type AssetSlotGroup = keyof typeof assets;
