// Generated by design-sheets ts-copy-module codegen. Do not edit by hand.
export const copyLocale = "en";

export const copy = {
  "game.title": "Template Game",
  "menu.play": "Play",
} as const;

export type CopyKey = keyof typeof copy;
