// Generated shell seed copy. Presentation-only changes replace this module;
// runtime behavior reads keys and never owns visible copy.
export const copyLocale = "en";

export const copy = {
  "game.title": "Trailhead",
  "currency.label": "Primary currency",
  "menu.settings": "Settings",
  "menu.subtitle": "A small adventure begins with one clear move.",
  "menu.hero": "Trailhead waypoint",
  "menu.progression": "Trail progress",
  "menu.start": "Trail start",
  "menu.play": "Continue",
  "menu.loading": "Preparing trail",
  "menu.level": "Trail",
  "menu.node.completed": "Complete",
  "menu.node.current": "Current",
  "menu.node.locked": "Locked",
  "level.label": "Trail",
  "level.pause": "Pause",
  "level.gameplay.label": "Starter mechanic socket",
  "level.gameplay.kicker": "Mechanic socket",
  "level.gameplay.title": "Make this moment yours",
  "level.gameplay.body": "Replace this starter socket with your game’s playable mechanic.",
  "level.sample.title": "Template diagnostics",
  "level.sample.body": "Preview the built-in win and retry paths.",
  "level.testWin": "Show win",
  "level.testLose": "Show retry",
  "settings.title": "Settings",
  "settings.back": "Back",
  "settings.music": "Music",
  "settings.sfx": "Sound effects",
  "settings.haptics": "Haptics",
  "pause.title": "Take a breather",
  "pause.resume": "Resume",
  "pause.settings": "Settings",
  "pause.home": "Home",
  "win.title": "Trail complete",
  "win.message": "A new path is ready to explore.",
  "win.next": "Next",
  "win.home": "Home",
  "fail.title": "Try that path again",
  "fail.message": "Your trail is waiting for another go.",
  "fail.retry": "Retry",
  "fail.home": "Home",
} as const;

export type CopyKey = keyof typeof copy;
