// Generated by the design-sheets round-trip. Do not edit by hand.
// Leaves are asset ids (basename of a file in design/assets/, ext stripped).
export const assets = {
  gameplay: {
    backgroundTile: "bb-background-tile",
    blockTileEmerald: "bb-block-tile-emerald",
    blockTileAzure: "bb-block-tile-azure",
    blockTileAmber: "bb-block-tile-amber",
    blockTileRuby: "bb-block-tile-ruby",
    blockTileMagenta: "bb-block-tile-magenta",
    blockTileViolet: "bb-block-tile-violet",
    blockTileTeal: "bb-block-tile-teal",
  },
  result: {
    ribbonWin: "ribbon-win",
    ribbonFail: "ribbon-fail",
  },
} as const;

export type AssetSlotGroup = keyof typeof assets;
