// Generated by design-sheets ts-copy-module codegen. Do not edit by hand.
export const copyLocale = "en";

export const copy = {
  "game.title": "Block Blast",
  "menu.play": "Play",
  "menu.endless": "Endless",
  "menu.best": "Best {score}",
  "menu.stage": "Stage {stage}",
  "menu.loading": "Loading stages",
  "hud.score": "Score",
  "hud.best": "Best",
  "hud.stage": "Stage",
  "hud.target": "Target",
  "hud.placements": "Moves",
  "hud.mode.endless": "Endless",
  "target.score": "Reach {target}",
  "target.placements": "Survive {target}",
  "action.pause": "Pause",
  "action.resume": "Resume",
  "action.menu": "Menu",
  "action.restart": "Restart",
  "action.retry": "Retry",
  "action.next": "Next",
  "action.settings": "Settings",
  "action.close": "Close",
  "settings.title": "Settings",
  "settings.music": "Music",
  "settings.sfx": "SFX",
  "settings.haptics": "Haptics",
  "result.win.title": "Cleared",
  "result.win.message": "Stage target reached.",
  "result.fail.title": "Blocked",
  "result.fail.message": "No piece can fit.",
  "result.score": "Score {score}",
} as const;

export type CopyKey = keyof typeof copy;
