// Generated by the design-sheets round-trip. Do not edit by hand.
// Hand-authored seed for the find_the_dog port. Leaves are asset ids (basename
// of a file in design/assets/, ext stripped); the runtime uses the byte-identical
// public/ui copies so the first v2 pass preserves the v1 visuals.
export const assets = {
  home: {
    banner: "home-banner-mascot-runtime",
    noAds: "no-ads-runtime",
    playButton: "play-level-button-runtime",
  },
  levelNode: {
    default: "level-node-locked-runtime",
    locked: "level-node-locked-bones-runtime",
    current: "node-current-candy",
    currentTeal: "level-node-current-teal-runtime",
    completed: "level-node-complete-runtime",
  },
  hud: {
    coin: "icon_coin",
    heart: "icon_heart",
    hint: "icon_hint_magnifier",
    settings: "settings-icon-runtime",
    shop: "shop-icon-runtime",
    back: "back_button",
  },
  resultModal: {
    detectiveComplete: "dog-detective-complete",
    detectiveCrying: "dog-detective-crying",
    title: "level-complete-title",
  },
  shop: {
    noAds: "shop_no_ads",
  },
  boot: {
    mascot: "dog-detective-openai",
  },
} as const;

export type AssetSlotGroup = keyof typeof assets;
