// Generated by the design-sheets round-trip. Do not edit by hand.
// Hand-authored seed for the marble_run pilot. Leaves are asset ids (the
// committed byte basenames under design/assets/, extension stripped); the
// design-sheets ingester indexes those bytes and the round-trip rewrites this
// module. The runtime URL resolution lives in theme.ts (Vite-resolved).
export const assets = {
  home: {
    banner: "marble-run-banner"
  },
  hud: {
    coin: "icon-marble-coin",
    replay: "icon-replay",
    gear: "icon-gear"
  },
  levelNode: {
    default: "level-node-default",
    locked: "level-node-locked",
    current: "level-node-current",
    completed: "level-node-completed"
  },
  resultModal: {
    ribbonFail: "ribbon-fail"
  }
} as const;

export type AssetSlotGroup = keyof typeof assets;
