// Generated by design-sheets ts-copy-module codegen. Do not edit by hand.
// Hand-authored seed for the marble_run pilot (extracted from v1 sugar3d
// dom.ts copy). The design-sheets round-trip replaces hand-editing later.
export const copyLocale = "en";

export const copy = {
  "app.title": "Marble Run",
  "menu.play": "Play",
  "menu.levels": "Levels",
  "menu.settings": "Settings",
  "saga.loading": "Loading levels",
  "hud.hint": "Hint",
  "hud.pause": "Pause",
  "settings.title": "Settings",
  "settings.music": "Music",
  "settings.sfx": "Sound Effects",
  "settings.haptics": "Haptics",
  "settings.back": "Back",
  "settings.close": "Close",
  "settings.restart": "Restart",
  "settings.home": "Home",
  "settings.reset": "Reset Progress",
  "result.win.title": "Level Complete",
  "result.win.reward": "Reward",
  "result.win.next": "Next",
  "result.win.finish": "Finish",
  "result.win.retry": "Replay",
  "result.finale.title": "All Marbles Sorted",
  "result.finale.message": "More levels are on the way!",
  "result.finale.action": "Awesome",
  "result.lose.title": "No Hearts Left",
  "result.lose.message": "Watch an ad to keep this run going.",
  "result.lose.watchAd": "Watch Ad",
  "result.lose.retry": "Retry",
  "result.lose.quit": "Quit",
  "pause.title": "Paused",
  "pause.resume": "Resume",
  "pause.settings": "Settings",
  "pause.quit": "Quit",
  "toast.routeBlocked": "That route is blocked",
  "toast.saveUnavailable": "Rewarded ad unavailable, try again later",
  "toast.streak": "Nice streak!",
  "connectivity.online": "Back online",
  "connectivity.offline": "You are offline"
} as const;

export type CopyKey = keyof typeof copy;
