// Generated shell seed copy. Presentation-only changes replace this module;
// runtime behavior reads keys and never owns visible copy.
export const copyLocale = "en";

export const copy = {
  "game.title": "Shell Proof Grapes",
  "currency.label": "Coins",
  "menu.settings": "Settings",
  "menu.subtitle": "A small adventure begins with one clear move.",
  "menu.hero": "A winding trail through green hills",
  "menu.progression": "Trail progress",
  "menu.start": "Trail start",
  "menu.play": "Continue",
  "menu.loading": "Preparing trail",
  "menu.level": "Trail",
  "menu.node.completed": "Complete",
  "menu.node.current": "Current",
  "menu.node.locked": "Locked",
  "level.label": "Trail",
  "level.pause": "Pause",
  "level.gameplay.label": "Trail clearing",
  "level.gameplay.kicker": "Trail clearing",
  "level.gameplay.title": "Find the next step",
  "level.gameplay.body": "A calm path opens ahead.",
  "level.sample.title": "Test outcomes",
  "level.sample.body": "Test-only outcome controls.",
  "level.testWin": "Win",
  "level.testLose": "Lose",
  "menu.shop": "Shop",
  "shop.title": "Shop",
  "shop.back": "Back",
  "shop.catalog": "Shop items",
  "shop.items": "Featured items",
  "currency.secondary.label": "Gems",
  "shop.purchase.pending": "Loading price",
  "shop.purchase.busy": "Please wait",
  "shop.purchase.unavailable": "Unavailable",
  "shop.restore.title": "Purchases",
  "shop.restore": "Restore purchases",
  "shop.restore.pending": "Restoring",
  "shop.restore.restored": "Restored",
  "shop.restore.status.idle": "Restore previous purchases.",
  "shop.restore.status.initializing": "Preparing the store.",
  "shop.restore.status.busy": "The store is busy.",
  "shop.restore.status.unavailable": "Restore is unavailable.",
  "shop.restore.status.pending": "Restoring purchases.",
  "shop.restore.status.restored": "Purchases restored.",
  "shop.restore.status.empty": "No purchases to restore.",
  "shop.restore.status.failed": "Restore failed.",
  "settings.title": "Settings",
  "settings.back": "Back",
  "settings.music": "Music",
  "settings.sfx": "Sound effects",
  "settings.haptics": "Haptics",
  "pause.title": "Trail paused",
  "pause.resume": "Resume",
  "pause.settings": "Settings",
  "pause.home": "Return home",
  "win.title": "Trail complete",
  "win.message": "A new path is ready to explore.",
  "win.next": "Next",
  "win.home": "Home",
  "fail.title": "Trail blocked",
  "fail.message": "Choose a clearer step, then try again.",
  "fail.retry": "Retry",
  "fail.home": "Home",
} as const;

export type CopyKey = keyof typeof copy;
