export const MENU_DECOR_BOARD_TILT_DEG = 15;
export const MENU_DECOR_CAMERA_YAW_DEG = 90 - MENU_DECOR_BOARD_TILT_DEG;
export const MENU_DECOR_FRAME_SCALE = 1.9;
export const MENU_DECOR_VIEW_OFFSET_Y_RATIO = 0.11;
