// Generated by design-sheets ts-copy-module codegen. Do not edit by hand.
// Hand-authored seed copied from the v1 UI strings that are visible in the
// port. The design-sheets round-trip replaces hand-editing later.
export const copyLocale = "en";

export const copy = {
  "game.title": "Test Game",
  "app.title": "Find the Dog",
  "menu.play": "Play",
  "menu.noAds": "No Ads",
  "menu.shop": "Shop",
  "menu.settings": "Settings",
  "saga.loading": "Loading levels",
  "hud.hint": "Hint",
  "hud.pause": "Pause",
  "shop.title": "Shop",
  "shop.coins": "Coins",
  "shop.hints": "Hints",
  "shop.noAds": "No Ads",
  "shop.restore": "Restore",
  "settings.title": "Settings",
  "settings.music": "Music",
  "settings.sound": "Sound",
  "settings.vibration": "Vibration",
  "settings.noAds": "No Ads",
  "settings.back": "Back",
  "settings.close": "Close",
  "settings.capture": "Capture",
  "result.win.title": "Level Complete",
  "result.win.next": "Next",
  "result.win.claim": "Claim",
  "result.win.double": "Claim x2",
  "result.lose.title": "Try Again",
  "result.lose.retry": "Retry",
  "result.lose.continue": "Continue",
  "result.lose.watchAd": "Watch",
  "toast.rewardUnavailable": "Rewarded ad unavailable, try again later",
  "connectivity.online": "Back online",
  "connectivity.offline": "You are offline",
} as const;

export type CopyKey = keyof typeof copy;
