export const EXISTING_FIND_THE_DOG_STATE_KEYS = [
  'analytics-first-open-claimed:find_the_dog',
  'ftd_reveal_pickup_v1',
  'ftd_wallet_purchase_checkpoint_v1',
  'ftd_wallet_coins',
  'ftd_wallet_counters',
  'ftd_wallet_no_ads_entitlement',
  'ftd_wallet_premium_entitlement',
  'ftd_wallet_reward_progress_count',
  'ftd_anon_id',
  'ftd_level',
  'ftd_settings',
  'ftd_hints',
  'ftd_total_levels_completed',
  'ftd_achievements',
  'ftd_tutorial_shown',
  'ftd_best_times',
  'ftd_wallet_processed_purchase_ids',
] as const;
