#!/usr/bin/env bash
# Generate a PR body from a Trello card + plan doc + git log on the
# current branch. Outputs markdown to stdout.
#
# Usage:
#   scripts/gen-pr-body.sh <trello-card-id> <plan-doc-path>
#   scripts/gen-pr-body.sh <trello-card-id> <plan-doc-path> --base main
#
# Requires: git.
#
# Output format mirrors what was hand-written 12 times in the
# 2026-04-14 trello-pipeline ftd sprint — Summary bullets pulled
# from plan goals/AC, Test plan checkboxes from plan verification,
# Trello link built from the card shortid.

set -euo pipefail

card_id="${1:-}"
plan_path="${2:-}"
base_branch="main"

while [[ $# -gt 2 ]]; do
  case "$3" in
    --base) base_branch="$4"; shift 2 ;;
    *) echo "unknown arg: $3" >&2; exit 2 ;;
  esac
done

if [[ -z "$card_id" || -z "$plan_path" ]]; then
  echo "usage: $0 <trello-card-id> <plan-doc-path> [--base <branch>]" >&2
  exit 2
fi

if [[ ! -f "$plan_path" ]]; then
  echo "error: $plan_path not found" >&2
  exit 1
fi

# Build the card URL directly from the shortid. The Trello short-link format
# is https://trello.com/c/<shortid>, so no CLI lookup is needed (the raw
# `trello` CLI is not installed — card ops go through `twf`/Trello REST). This
# keeps the advertised `Trello:` line populated instead of silently empty.
card_url="https://trello.com/c/${card_id}"

# Extract plan title (first H1)
plan_title="$(awk '/^# / { sub(/^# /, ""); print; exit }' "$plan_path")"

# Extract goals / AC bullets from the plan: first ## section that
# contains bullets, take top 3
plan_summary="$(awk '
  /^## / { if (got_bullets) exit; section=$0; next }
  /^[[:space:]]*-[[:space:]]/ {
    if (count < 3) {
      print
      count++
      got_bullets=1
    }
  }
' "$plan_path")"

# Extract test plan items if a Verification / Test plan section exists
test_plan="$(awk '
  /^## (Verification|Test plan|Test Plan|Tests?)/ { capturing=1; next }
  capturing && /^## / { exit }
  capturing && /^[[:space:]]*-[[:space:]]/ {
    line=$0
    sub(/^[[:space:]]*-[[:space:]]/, "- [ ] ", line)
    print line
  }
' "$plan_path")"

# Recent commits on this branch since base
commit_log="$(git log --oneline "$base_branch..HEAD" 2>/dev/null | head -10 || true)"

# Compose the PR body
cat <<EOF
${card_url:+Trello: $card_url}

## Summary
${plan_summary:-- (auto-generated from $plan_path — plan has no bullet summary; fill in)}

## Test plan
${test_plan:-- [ ] Manual verification on device}

## Commits
\`\`\`
${commit_log:-(no commits between $base_branch and HEAD)}
\`\`\`

---
*Generated by \`scripts/gen-pr-body.sh\` (bundled with trello-pipeline skill). Edit before opening the PR if anything reads off — starting point, not contract.*
EOF
