""""""

# AUTOGENERATED by nbsync — DO NOT EDIT. Source: ../nbs/utils/hitboxes.ipynb
#
# LLM EDITING GUIDE:
# - Edit code within existing cell blocks (between # %% markers)
# - To add a new code cell:    # %% new
# - To add a markdown cell:    # %% [markdown] new
#   (markdown lines use '# ' prefix, e.g. '# ## Heading')
# - Cells marked [notebook-only] are visible for context but not editable
# - Do not modify __all__ or this header — they are regenerated
# - Run `nbsync p2n` to sync your .py edits back to the notebook

# %% auto 0
__all__ = ['Hitbox', 'Rect', 'generate_hitboxes', 'generate_hitboxes_grounded', 'draw_mask_overlay']

# %% nbs/utils/hitboxes.ipynb 0
#| default_exp utils.hitboxes


# %% [markdown] nbs/utils/hitboxes.ipynb 1 [notebook-only: "# Hitboxes — Dog Placement"]
# %% nbs/utils/hitboxes.ipynb 2
import random
from dataclasses import dataclass

from PIL import Image, ImageDraw


@dataclass(frozen=True)
class Rect:
    """An axis-aligned rectangle (x, y is top-left corner)."""
    x: int
    y: int
    w: int
    h: int

    def contains_circle(self, cx: int, cy: int, r: int) -> bool:
        """Check if a circle overlaps this rectangle."""
        # Closest point on rect to circle center
        closest_x = max(self.x, min(cx, self.x + self.w))
        closest_y = max(self.y, min(cy, self.y + self.h))
        dx = cx - closest_x
        dy = cy - closest_y
        return (dx * dx + dy * dy) < r * r

    def overlaps_box(self, left: float, top: float, right: float, bottom: float) -> bool:
        """Check if this rectangle overlaps an axis-aligned box."""
        return left < self.x + self.w and right > self.x and top < self.y + self.h and bottom > self.y


@dataclass(frozen=True)
class Hitbox:
    """A circular region where a dog will be placed."""
    x: int
    y: int
    radius: int


def generate_hitboxes(
    n: int,
    width: int,
    height: int,
    radius_range: tuple[int, int] = (30, 30),
    margin: int = 20,
    seed: int | None = None,
) -> list[Hitbox]:
    """Generate n non-overlapping hitboxes at random positions.

    Each hitbox is placed at least `margin` px from the image edge,
    and hitboxes don't overlap (center distance > sum of radii).
    """
    rng = random.Random(seed)
    hitboxes: list[Hitbox] = []

    for _ in range(n * 200):
        r = rng.randint(*radius_range)
        x = rng.randint(margin + r, width - margin - r)
        y = rng.randint(margin + r, height - margin - r)

        if any(
            ((x - h.x) ** 2 + (y - h.y) ** 2) ** 0.5 < r + h.radius
            for h in hitboxes
        ):
            continue

        hitboxes.append(Hitbox(x=x, y=y, radius=r))
        if len(hitboxes) == n:
            break

    if len(hitboxes) != n:
        raise ValueError(
            f"Could only place {len(hitboxes)} of {n} requested hitboxes"
        )
    return hitboxes


def generate_hitboxes_grounded(
    n: int,
    width: int,
    height: int,
    radius_range: tuple[int, int] = (25, 40),
    margin: int = 20,
    seed: int | None = None,
    top_fraction: float = 0.0,
    forbidden: list[Rect] | None = None,
    min_distance_multiplier: float = 2.0,
    square_padding_multiplier: float | None = None,
) -> list[Hitbox]:
    """Generate non-overlapping hitboxes within the image bounds.

    top_fraction: fraction of image height to exclude from the top (0.0 = no exclusion).
    forbidden: list of Rect regions where hitboxes must not overlap.
    min_distance_multiplier: minimum center-to-center distance as a multiple of the
        larger radius. 2.0 means inpainting crops (1.5x padding) won't overlap.
    square_padding_multiplier: when set, also reject placements whose padded
        square crop overlaps another padded square crop or a forbidden rectangle.
    """
    rng = random.Random(seed)
    hitboxes: list[Hitbox] = []
    min_y = int(height * top_fraction)
    forbidden = forbidden or []

    for _ in range(n * 200):
        r = rng.randint(*radius_range)
        x = rng.randint(margin + r, width - margin - r)
        y = rng.randint(max(margin + r, min_y), height - margin - r)
        square_half = r * square_padding_multiplier if square_padding_multiplier is not None else None

        # Check forbidden zones
        if any(rect.contains_circle(x, y, r) for rect in forbidden):
            continue
        if square_half is not None and any(
            rect.overlaps_box(x - square_half, y - square_half, x + square_half, y + square_half)
            for rect in forbidden
        ):
            continue

        if any(
            ((x - h.x) ** 2 + (y - h.y) ** 2) ** 0.5 < max(r, h.radius) * min_distance_multiplier
            for h in hitboxes
        ):
            continue
        if square_half is not None and any(
            abs(x - h.x) < square_half + h.radius * square_padding_multiplier
            and abs(y - h.y) < square_half + h.radius * square_padding_multiplier
            for h in hitboxes
        ):
            continue

        hitboxes.append(Hitbox(x=x, y=y, radius=r))
        if len(hitboxes) == n:
            break

    return hitboxes


def draw_mask_overlay(bg: Image.Image, hitboxes: list[Hitbox]) -> Image.Image:
    """Draw magenta ellipses on the background at each hitbox position.

    Used by the magenta overlay approach — marks where Gemini should paint dogs.
    """
    composite = bg.copy()
    draw = ImageDraw.Draw(composite)
    for h in hitboxes:
        draw.ellipse(
            [h.x - h.radius, h.y - h.radius, h.x + h.radius, h.y + h.radius],
            fill=(255, 0, 255),
        )
    return composite


# %% nbs/utils/hitboxes.ipynb 3 [notebook-only: "# Try it out"]
