""""""

# AUTOGENERATED by nbsync — DO NOT EDIT. Source: ../nbs/utils/image_ops.ipynb
#
# LLM EDITING GUIDE:
# - Edit code within existing cell blocks (between # %% markers)
# - To add a new code cell:    # %% new
# - To add a markdown cell:    # %% [markdown] new
#   (markdown lines use '# ' prefix, e.g. '# ## Heading')
# - Cells marked [notebook-only] are visible for context but not editable
# - Do not modify __all__ or this header — they are regenerated
# - Run `nbsync p2n` to sync your .py edits back to the notebook

# %% auto 0
__all__ = ['_crop_box', '_extract_dog_pixels', '_make_circle_mask', 'evaluate_hitboxes']

# %% nbs/utils/image_ops.ipynb 0
#| default_exp utils.image_ops


# %% [markdown] nbs/utils/image_ops.ipynb 1 [notebook-only: "# Image Operations"]
# %% nbs/utils/image_ops.ipynb 2
import numpy as np
from PIL import Image, ImageDraw

from levelbuilder.hitboxes import Hitbox


def _crop_box(h: Hitbox, img_w: int, img_h: int, padding: float = 1.5) -> tuple[int, int, int, int]:
    """Return (left, upper, right, lower) for a square crop around a hitbox.

    padding=1.5 means the crop extends 1.5x the radius on each side of center,
    so the total side length is 3x the radius. Clamped to image bounds.
    """
    half = int(h.radius * padding)
    left = max(h.x - half, 0)
    upper = max(h.y - half, 0)
    right = min(h.x + half, img_w)
    lower = min(h.y + half, img_h)
    return (left, upper, right, lower)


def _extract_dog_pixels(
    before: Image.Image,
    after: Image.Image,
    threshold: int = 30,
) -> Image.Image:
    """Create a mask of pixels that changed between before and after.

    Returns a grayscale mask where white = changed (dog), black = unchanged (background).

    This is the core of the "extract and paste" technique:
    1. Crop original background (before)
    2. Send to Gemini to draw a dog (after)
    3. Diff to find what changed → dog mask
    4. Paste only the dog pixels onto the untouched original

    Threshold controls sensitivity:
    - Higher (40-50) = only keep large changes, cleaner mask, may clip dog edges
    - Lower (15-25) = keep subtle edges, may include background noise
    - Default 30 is the sweet spot from autoresearch calibration
    """
    # Ensure both images are RGB to prevent RGBA alpha channel pollution
    before_rgb = before.convert("RGB") if before.mode != "RGB" else before
    after_rgb = after.convert("RGB") if after.mode != "RGB" else after
    before_arr = np.array(before_rgb, dtype=np.int16)
    after_arr = np.array(after_rgb, dtype=np.int16)
    diff = np.abs(after_arr - before_arr).max(axis=2)
    mask = (diff > threshold).astype(np.uint8) * 255
    return Image.fromarray(mask, mode="L")


def _make_circle_mask(
    crop_size: tuple[int, int],
    hb: Hitbox,
    box: tuple[int, int, int, int],
    padding_px: int = 20,
) -> Image.Image:
    """Create a white-on-black circle mask for a cropped region.

    Used by Flux mask-based inpainting. The mask is padded beyond the
    hitbox radius for better blending at edges.
    """
    mask = Image.new("L", crop_size, 0)
    draw = ImageDraw.Draw(mask)
    local_cx = hb.x - box[0]
    local_cy = hb.y - box[1]
    r = hb.radius + padding_px
    draw.ellipse(
        [local_cx - r, local_cy - r, local_cx + r, local_cy + r],
        fill=255,
    )
    return mask


def evaluate_hitboxes(image: Image.Image, hitboxes: list[Hitbox], opacity: float = 0.5) -> Image.Image:
    """Overlay semi-transparent magenta hitbox circles on an image.

    Useful for visually checking whether dogs actually landed inside their hitboxes.
    Green = good placement. If the dog is outside the circle, the placement failed.
    """
    base = image.convert("RGBA")
    circles = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(circles)
    alpha = int(255 * opacity)
    for h in hitboxes:
        draw.ellipse(
            [h.x - h.radius, h.y - h.radius, h.x + h.radius, h.y + h.radius],
            fill=(255, 0, 255, alpha),
            outline=(255, 0, 255, 255),
            width=2,
        )
    return Image.alpha_composite(base, circles).convert("RGB")


