""""""

# AUTOGENERATED by nbsync — DO NOT EDIT. Source: ../nbs/utils/cache.ipynb
#
# LLM EDITING GUIDE:
# - Edit code within existing cell blocks (between # %% markers)
# - To add a new code cell:    # %% new
# - To add a markdown cell:    # %% [markdown] new
#   (markdown lines use '# ' prefix, e.g. '# ## Heading')
# - Cells marked [notebook-only] are visible for context but not editable
# - Do not modify __all__ or this header — they are regenerated
# - Run `nbsync p2n` to sync your .py edits back to the notebook

# %% auto 0
__all__ = ['_hash_arg', 'image_cache']

# %% nbs/utils/cache.ipynb 0
#| default_exp utils.cache


# %% [markdown] nbs/utils/cache.ipynb 1 [notebook-only: "# Image Cache"]
# %% nbs/utils/cache.ipynb 2
from pathlib import Path
import os
from functools import wraps
import hashlib

from PIL import Image

# Notebook-era cache. In the fork this resolved to `tools/nbs/.cache` —
# OUTSIDE the tool, polluting the repo's tools/ dir on every import. Keep it
# inside the tool, and create it lazily so merely importing the module (which
# every route does, via prompts) touches no filesystem.
CACHE_DIR = Path(
    os.environ.get("LEVEL_EDITOR_IMAGE_CACHE")
    or Path(__file__).resolve().parent.parent / ".cache" / "images"
)


def _ensure_cache_dir() -> Path:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    return CACHE_DIR


def _hash_arg(arg) -> bytes:
    """Return bytes that uniquely represent an argument for cache keying."""
    if isinstance(arg, Image.Image):
        return arg.tobytes()
    return repr(arg).encode()


def image_cache(fn):
    """Decorator for functions that return a PIL Image.

    Adds a `cached: bool = False` kwarg. When True, loads the last saved
    result from .cache/<fn_name>_<args_hash>.png instead of calling the function.
    Every successful call saves its result to cache regardless.

    Cache key = md5 hash of all args/kwargs. Different inputs get different entries.
    PIL Images are hashed by pixel data, everything else by repr().
    """
    @wraps(fn)
    def wrapper(*args, cached: bool = False, **kwargs) -> Image.Image:
        h = hashlib.md5()
        for a in args:
            h.update(_hash_arg(a))
        for k in sorted(kwargs):
            h.update(k.encode())
            h.update(_hash_arg(kwargs[k]))
        key = f"{fn.__name__}_{h.hexdigest()[:12]}"
        path = _ensure_cache_dir() / f"{key}.png"
        if cached and path.exists():
            return Image.open(path)  # preserve original mode (RGB or RGBA)
        img = fn(*args, **kwargs)
        img.save(path)
        return img
    return wrapper


